# KAPSAMLI DİYANET VERİTABANI - TÜM ALT BAŞLIKLAR
# Nafile namazlar, Abdest, Gusül, Teyemmüm, Hayız-Nifas ve tüm detaylar

COMPREHENSIVE_DIYANET_QA = [
    # ============ NAFİLE NAMAZLAR ============
    {
        "category": "namaz",
        "question": "Nafile namaz nedir?",
        "answer": "Nafile namazlar, farz ve vacip dışında kılınan isteğe bağlı namazlardır.\n\n**NAFİLE NAMAZ ÇEŞİTLERİ:**\n\n**1. TAHİYYETÜL-MESCİD:**\n• Camiye girildiğinde\n• 2 rekat\n• Camiye selam için\n\n**2. DUHA (KUŞLUK):**\n• Güneş doğduktan sonra\n• 2-12 rekat\n• Kuşluk vakti\n\n**3. İŞRAK:**\n• Güneş doğduktan 45 dk sonra\n• 2 rekat\n• Sabah namazı sonrası\n\n**4. EVVÂBÎN:**\n• Akşam-Yatsı arası\n• 6-20 rekat\n• Tövbe namazı\n\n**5. TESBİH NAMAZI:**\n• 4 rekat\n• Özel tesbihler\n• Çok sevaplı\n\n**6. TEHECCÜD:**\n• Gece uyanarak\n• 2-12 rekat\n• En faziletli nafile\n\n**7. HACET:**\n• İhtiyaç için\n• 4+4+2 rekat\n• Dua ile\n\n**8. İSTİHARE:**\n• Karar için\n• 2 rekat\n• Özel dua\n\n**9. TÖVBE:**\n• Günah sonrası\n• 2 rekat\n• Pişmanlıkla\n\n**10. ŞÜKÜR:**\n• Nimet için\n• 2 rekat\n• Şükür ile\n\nNafile namazlar sevap kazandırır ve günahları siler.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Duha (Kuşluk) namazı nasıl kılınır?",
        "answer": "Duha namazı, kuşluk vaktinde kılınan nafile namazdır.\n\n**VAKTİ:**\n• Güneş doğduktan 45 dakika sonra\n• Öğle vaktine kadar\n• En faziletli: Kuşluk zamanı (sıcaklaşınca)\n\n**REKAT SAYISI:**\n• En az: 2 rekat\n• En çok: 12 rekat\n• Tavsiye: 4-8 rekat\n• İkişer ikişer kılınır\n\n**KILINIŞ ŞEKLİ:**\n• Normal namaz gibi\n• İkişer rekat selam\n• Fatiha + Sure\n• Tesbihat\n\n**FAZİLETİ:**\n\nHz. Peygamber: 'Kim kuşluk namazını kılarsa, gün boyunca o kişiye kifayet edilir.'\n\n'Sabah namazını cemaatle kılıp güneş doğuncaya kadar oturur, sonra 2 rekat namaz kılarsa, tam bir hac ve umre sevabı kazanır.' (İşrak)\n\n**SEVİYATI:**\n• 360 sadaka sevabı\n• Günlük bağışlanma\n• Rızık bereketi\n• Şifa vesilesi\n\n**HİKMETİ:**\n• Sabah namazı sonrası ibadet\n• Rızkını Allah'tan istemek\n• Gün boyunca bereket\n\n**OKUNAN SURELER:**\n• İhlas, Felak, Nas\n• Kafirun\n• Kısa sureler\n\n**DUA:**\nSonunda istiğfar ve dua edilir.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Tesbih namazı nasıl kılınır?",
        "answer": "Tesbih namazı, özel tesbihlerle kılınan 4 rekatlık nafile namazdır.\n\n**REKAT SAYISI:**\n• 4 rekat birlikte\n• Tek selamla\n• İki oturuşla\n\n**TESBİH SAYISI:**\nHer rekatta **75 defa** tesbih:\n• Sübhanallah (25)\n• Elhamdülillah (25)\n• Allahu Ekber (25)\nToplam: 4 x 75 = **300 tesbih**\n\n**KILINIŞ ŞEKLİ:**\n\n**1. Rekat:**\n• Sübhaneke okunduktan sonra: 15 tesbih\n• Eûzü-besmele-Fatiha-Sure sonrası: 10 tesbih\n• Rükûda: 10 tesbih\n• Rükûdan sonra: 10 tesbih\n• Secdede: 10 tesbih\n• İki secde arası: 10 tesbih\n• İkinci secdede: 10 tesbih\nToplam: 75\n\n**2-3-4. Rekatlar:**\n• Aynı şekilde\n• Her biri 75 tesbih\n\n**TESBİH METNİ:**\n'Sübhanallahi velhamdülillahi ve lâ ilâhe illallahu vallahu ekber'\n\nVeya kısa:\n'Sübhanallah, Elhamdülillah, Allahu Ekber'\n\n**FAZİLETİ:**\nHz. Peygamber (Hz. Abbas'a): 'Eğer günde bir kez kılarsan günahların bağışlanır. Kılamazsan haftada bir, onu da kılamazsan ayda bir, onu da kılamazsan yılda bir kıl.'\n\n**NE ZAMAN KILINIR:**\n• Mekruh vakitler dışında her zaman\n• Tercihan gece\n• Teheccüd vakti\n\n**UNUTURSA:**\n• Secdeden sonra hatırlarsa orada oku\n• Sehiv secdesi gerekmez\n• Sayıyı tamamlamaya çalış",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Tahiyyetül-mescid namazı nedir?",
        "answer": "Tahiyyetül-mescid, camiye girildiğinde kılınan 2 rekatlık nafile namazdır.\n\n**ANLAMI:**\n'Mescide selam namazı'\nCamiye saygı ve selam\n\n**NE ZAMAN KILINIR:**\n• Camiye her girildiğinde\n• Oturmadan önce\n• Hemen kılınmalı\n\n**REKAT SAYISI:**\n• 2 rekat\n• Tek selam\n• Kısa surelerle\n\n**KILINIŞ:**\n• Normal namaz gibi\n• Fatiha + kısa sure\n• Hızlıca kılınabilir\n\n**FAZİLETİ:**\n\nHz. Peygamber: 'Biriniz camiye girdiğinde, oturmadan önce 2 rekat namaz kılsın.'\n\n**MEKRUH VAKİTLERDE:**\n• Güneş doğarken: Kılınmaz\n• Tepe vakti: Kılınmaz\n• Batarken: Kılınmaz\n• Cuma hutbesi: Kılınır (istisna)\n\n**CUMA GÜNÜ:**\n• Hutbe okunurken bile kılınır\n• İmam minberde iken\n• Hızlıca 2 rekat\n• Otur ve dinle\n\n**ÖZEL DURUMLAR:**\n• Namaz kılınacaksa: Gerek yok\n• Sünnet kılacaksa: Tahiyyetül-mescid yerine geçer\n• Farz namaza yakınsa: Sünnet yeterli\n\n**HİKMETİ:**\n• Camiye saygı\n• Namaza hazırlık\n• Allah'a yönelme\n• Bereket\n\n**BAŞKA İSMİ:**\n• Tahiyyetül-mescid\n• Tahiyye namazı\n• Mescid selamı\n\nCamiye giren Müslüman, oturmadan önce bu namazı kılmalıdır.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Evvabîn namazı nedir?",
        "answer": "Evvabîn, akşam ile yatsı arasında kılınan nafile namazdır.\n\n**ANLAMI:**\n'Çok tövbe edenlerin namazı'\nEvvâb: Çok tövbe eden\n\n**VAKTİ:**\n• Akşam namazından sonra\n• Yatsı namazına kadar\n• Tercihan akşam sünnetinden sonra\n\n**REKAT SAYISI:**\n\n**1. Görüş (Yaygın):**\n• 6 rekat\n• İkişer ikişer\n• 3 selam\n\n**2. Görüş:**\n• 20 rekat\n• İkişer ikişer\n• 10 selam\n\n**3. Görüş (Minimum):**\n• 2 rekat\n\n**FAZİLETİ:**\n\nHz. Peygamber: 'Kim akşam namazından sonra 6 rekat namaz kılar ve aralarında kötü bir söz söylemezse, o namazlar 12 yıllık ibadete denk gelir.'\n\n**KILINIŞ:**\n• Normal nafile gibi\n• Fatiha + sure\n• İkişer rekat\n• Her 2 rekatta selam\n\n**HİKMETİ:**\n• Tövbe namazı\n• Günlük günahlardan arınma\n• Allah'a yönelme\n• Gece ibadetine hazırlık\n\n**DİĞER İSİMLER:**\n• Evvabîn\n• Akşam-yatsı arası nafile\n• Tövbe namazı\n\n**TAVSİYE:**\n• Akşam sünnetinden sonra kıl\n• Yatsıya kadar\n• Camide veya evde\n• İhlasla ve huşu ile\n\n**UNUTMA:**\nBu namaz, o gün işlenen günahlardan temizlenme niyetiyle kılınır.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    
    # ============ ABDEST, GUSÜL, TEYEMMÜM ============
    {
        "category": "namaz",
        "question": "Abdest bozan durumlar nelerdir?",
        "answer": "Abdesti bozan durumlar:\n\n**KESİN BOZAN DURUMLAR:**\n\n**1. TUVALET İHTİYACI:**\n• İdrar (çiş)\n• Dışkı\n• Rüzgâr (gaz çıkması)\n• Meni (cünüplük - gusül gerekir)\n• Mezi (şehvet suyu)\n• Vedi (idrar sonrası sıvı)\n\n**2. UYUMAK:**\n• Yatarak uyumak\n• Yaslanarak uyumak\n• Oturarak derin uyku\n• Bilinç kaybı\n• Bayılmak\n• Sara nöbeti\n\n**3. AKIL KAYBETME:**\n• Sarhoşluk\n• Bayılma\n• Uyuşturucu\n• Delilik\n\n**4. KANAMA:**\n• Burundankınir kan\n• Yaradan akan kan (çok ise)\n• Kusmuk (ağız dolusu)\n• Hayız (adet)\n• Nifas (lohusalık)\n\n**5. CİNSEL TEMAS:**\n• Şehvetle dokunma\n• Öpüşme (şehvetle)\n• Cinsel ilişki (gusül gerekir)\n\n**TARTIŞMALI DURUMLAR:**\n\n**Kadına/Erkeğe Dokunmak:**\n• Hanefi: Dokunma bozmaz (şehvetsiz)\n• Şafii: Dokunma bozar\n• Eşe şehvetsiz dokunma: Çoğunluğa göre bozmaz\n\n**Gülmek:**\n• Namazda kahkaha: Bozar (Hanefi)\n• Namaz dışında: Bozmaz\n• Tebessüm: Hiç bozmaz\n\n**Deve Eti Yemek:**\n• Hanbeli: Bozar\n• Diğerleri: Bozmaz\n\n**BOZMAYAN DURUMLAR:**\n✅ Yemek yemek\n✅ Su içmek\n✅ Konuşmak\n✅ Gülmek (namaz dışı)\n✅ Ağlamak\n✅ Kulaklık takmak\n✅ Düşmek (uyumadan)\n✅ Burnuna kaçırmak (çıkmazsa)\n✅ Az kan (damla)\n✅ İğne olmak\n✅ Diş çektirmek (az kan)\n✅ Koku sürmek\n✅ Eşe şehvetsiz dokunmak (Hanefi)\n\n**ŞÜPHELİ DURUMLAR:**\n• Şüphen varsa abdestlisin\n• Kesin bilmeden yenilenmez\n• 'Belki bozuldu' yetmez\n• Emin olmalısın\n\n**DİYANET TAVSİYESİ:**\nŞüphe üzerine abdest yenilenmez. Kesin bozulduğundan emin olunmalıdır.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Gusül nasıl alınır ve ne zaman gerekir?",
        "answer": "Gusül (boy abdesti), bütün vücudun yıkanmasıdır.\n\n**GUSÜL GEREKTİREN DURUMLAR:**\n\n**1. CÜNÜPLÜK:**\n• Cinsel ilişki\n• İhtilam (rüyada boşalma)\n• Meni çıkması\n• Şehvetle dokunma sonucu\n\n**2. HAYIZ (ADET):**\n• Kadının adetin bitmesi\n• Kanamanın kesilmesi\n• Temizlenme\n\n**3. NİFAS (LOHUSALIK):**\n• Doğum sonrası kanamanın bitmesi\n• 40 gün veya kanama bitimi\n\n**GUSÜLÜN FARZLARI (3):**\n\n**1. Ağız Çalkalamak:**\n• Ağza su almak\n• Boğaza kadar\n• Tüm ağız ıslanmalı\n\n**2. Burun Temizlemek:**\n• Buruna su çekmek\n• Yumuşak kemiğe kadar\n• Temizlemek\n\n**3. Bütün Vücudu Yıkamak:**\n• Hiçbir yer kuru kalmamalı\n• Saç dipleri\n• Kulak içi\n• Göbek\n• Parmak aralarıır\n• Her yer ıslanmalı\n\n**GUSÜL ALIŞ ŞEKLİ:**\n\n**1. Niyet:**\n'Cünüplükten gusletmeye niyet ettim'\n\n**2. Besmele:**\n'Bismillahirrahmanirrahim'\n\n**3. Elleri Yıka:**\n• 3 defa\n• Bileklere kadar\n\n**4. Özel Bölge:**\n• Temizle\n• Pisliği gider\n\n**5. Abdest Al:**\n• Tam abdest\n• Ayaklar hariç (sona bırak)\n\n**6. Başı Yıka:**\n• 3 defa\n• Saç diplerine su ulaştır\n• Ovmadan\n\n**7. Sağ Taraf:**\n• 3 defa\n• Tüm sağ vücut\n\n**8. Sol Taraf:**\n• 3 defa\n• Tüm sol vücut\n\n**9. Ayaklar:**\n• Her iki ayağı yıka\n• Topukları da\n\n**SÜNNETLERİ:**\n• Başı 3 kez yıkamak\n• Sağ-sol sırası\n• Ovuşturmak\n• Temiz yerde\n• Kıbleye dönmek\n\n**HIZLI GUSÜL:**\n• Sadece farzları yap\n• Ağız çalkala\n• Burun temizle\n• Tüm vücut ıslansın\n• Yeterli\n\n**SÜNNET GUSÜLLER:**\n• Cuma günü\n• Bayram günleri\n• Hac için (ihram)\n• Cuma'da günceleştirme\n• Cenaze yıkayan\n\n**DİKKAT:**\nGusülsüz namaz kılınamaz, oruç tutulmaz, Kur'an'a dokunulmaz.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Teyemmüm nasıl yapılır?",
        "answer": "Teyemmüm, su olmadığında veya kullanılamadığında yapılan kuru abdest/gusüldür.\n\n**NE ZAMAN YAPILIR:**\n\n**1. Su Yoksa:**\n• Seyahatte su bulamazsa\n• Çölde, kırda\n• Su satın alamazsa\n\n**2. Su Zararlıysa:**\n• Hasta (su kullanırsa kötüleşir)\n• Yaralı (yara ıslanmamalı)\n• Çok soğuk (donma riski)\n• Alerji\n\n**3. Su Yetmezse:**\n• Az su var (sadece içmek için)\n• Susuz kalma riski\n\n**4. Vakit Darsa:**\n• Namaz vakti çıkacak\n• Cenaze namazı kaçacak\n\n**TEYEMMÜMÜNillahN FARZLARI (4):**\n\n**1. Niyet:**\n'Abdest/gusül yerine teyemmüme niyet ettim'\n\n**2. İki El Vurma:**\n• Temiz toprağa\n• Veya taş, kum, duvar\n• İki kez vurmak\n\n**3. Yüzü Meshetek:**\n• İlk vuruştan sonra\n• Tüm yüzü\n• Saç bitimi-çene-kulak\n\n**4. Kollları Mesh:**\n• İkinci vuruştan sonra\n• Dirseklere kadar\n• Önce sağ, sonra sol\n\n**YAPILIŞ ŞEKLİ:**\n\n**Adım 1:**\n• Niyet et\n• Besmele çek\n\n**Adım 2:**\n• Elleri toprağa vur\n• Hafifçe silkele (toz için)\n• Yüzü mesh et\n\n**Adım 3:**\n• Elleri tekrar toprağa vur\n• Sağ eli ile sol kolu mesh\n• Sol eli ile sağ kolu mesh\n• Dirseklere kadar\n\n**TEYEMMÜM İLE:**\n✅ Namaz kılınır\n✅ Kur'an okunur\n✅ Kur'an'a dokunulur\n✅ Cami girilir\n\n**TEYEMMÜM BOZULUR:**\n• Su bulunca\n• Abdest bozan şeyler\n• Zaruret kalınca\n\n**HANGİ TOPRAĞA:**\n✅ Toprak\n✅ Kum\n✅ Taş\n✅ Duvar (sıvalı)\n✅ Fayans (tozlu)\n❌ Ahşap\n❌ Plastik\n❌ Metal\n❌ Cam\n\n**MESH NEDİR:**\n• Islak elle dokunmak değil\n• Eli yüzeye sürmek\n• Hafifçe dokunmak\n\n**GUSÜL YERİNE:**\n• Aynı teyemmüm\n• Hem abdest hem gusül yerine geçer\n• Tek teyemmüm yeterli\n\n**TAVSİYE:**\nTeyemmüm son çare olmalı. Su varsa mutlaka abdest alınmalı.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Hayız ve nifas halindeki kadınlar ne yapmalı?",
        "answer": "Hayız (adet) ve nifas (lohusalık) kadınlar için özel hükümler vardır.\n\n**HAYIZ (ADET) NEDİR:**\n• Kadının aylık kanaması\n• Doğal biyolojik süreç\n• Genelde 3-10 gün\n• Kişiye göre değişir\n\n**NİFAS (LOHUSALIK):**\n• Doğum sonrası kanama\n• 40 güne kadar\n• Erken bitebilir\n• Kanama bitince biter\n\n**HAYIZ/NİFASTA YASAKLAR:**\n\n❌ **1. NAMAZ:**\n• Namaz kılınamaz\n• Kaza da yoktur\n• Bağışlanır\n\n❌ **2. ORUÇ:**\n• Oruç tutulamaz\n• Sonra kaza edilir\n• Ramazan'dan sonra\n\n❌ **3. KUR'AN DOKUNMA:**\n• Mushaf'a dokunulamaz\n• Ezberden okumak: Tartışmalı\n• Hanefi: Ezberden de okumaz\n• Şafii: Ezberden okuyabilir\n\n❌ **4. CİNSEL İLİŞKİ:**\n• Kesinlikle yasak\n• Büyük günah\n• Kanama bitene kadar\n\n❌ **5. CAMİYE GİRME:**\n• Mescide girilmez\n• İhtiyaç varsa tartışmalı\n• Geçmek caiz (bazılarına göre)\n\n❌ **6. TAVAF:**\n• Kâbe tavafı yapılamaz\n• Hac/umre erteler\n\n**YAPABİLECEKLER:**\n\n✅ **1. ZİKİR:**\n• Sübhanallah\n• Elhamdülillah\n• Allahu Ekber\n• Tesbih çekmek\n\n✅ **2. DUA:**\n• Dua etmek\n• İstiğfar\n• Salavat\n\n✅ **3. DİNİ KİTAP:**\n• Tefsir okumak\n• Hadis okumak\n• Fıkıh kitapları\n\n✅ **4. DİNLEMEKakr:**\n• Kur'an dinlemek\n• Vaaz dinlemek\n• Sohbet\n\n✅ **5. SADAKA:**\n• Hayır işleri\n• Yardım\n• İyilik\n\n**TEMİZLENİNCE:**\n\n**1. Kanama Bitmeli:**\n• Tamamen kesilmeli\n• Beyaz akıntı (bezde)\n\n**2. Gusül Alınmalı:**\n• Tam gusül\n• 3 farz\n• Tüm vücut\n\n**3. İbadetlere Başla:**\n• Hemen namaza başla\n• Oruç tutabilir\n• Kur'an okuyabilir\n\n**İSTİHAZA (Sürekli Kanama):**\n• Normal hayız süresi dışı\n• Hastalık kanaması\n• İbadet edilir\n• Abdest alınır\n• Bir pamuk ile\n\n**HAMİLELİKTE KANAMA:**\n• Gebelikte kanama hayız değil\n• İstihaza sayılır\n• Namaz kılınır\n• Doktora danışılmalı\n\n**KAZA ORUC:**\n• Ramazan'da tutamayanları\n• Sonradan kaza et\n• Yeni Ramazan'dan önce\n• Süre var\n\n**ÖNEMLİ:**\nHayız ve nifas Allah'ın takdiridir. Kadınlar bu dönemde günahkar değildir, aksine namaz kılmamaları farzdır.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Özürlü (mazur) kimse nasıl namaz kılar?",
        "answer": "Özürlü (mazur) kişiler durumlarına göre namaz kılarlar.\n\n**ÖZÜR (MAZERET) ÇEŞİTLERİ:**\n\n**1. ABDESTSİZ KALMA ÖZRÜ:**\n• Sürekli idrar kaçırma\n• Kontrol edilemeyen gaz\n• Sürekli kanama\n• İshal\n\n**Hüküm:**\n• Her namaz için bir abdest\n• Vakit girmeden abdest al\n• Namaz kıl\n• Vakit çıkana kadar geçerli\n• Tekrar aksa devam et\n\n**2. AYAKTA DURAMAMA:**\n• Hasta\n• Yaşlı\n• Bacak problemi\n• Ameliyat\n\n**Hüküm:**\n• Oturarak kıl\n• Sandalyede\n• Yatakta\n• Rükû-secde eğerek\n\n**3. RÜKÛ-SECDE YAPAMAMA:**\n• Bel fıtığı\n• Diz ağrısı\n• Ameliyat\n\n**Hüküm:**\n• İşaretle kıl\n• Başla işaret\n• Secde rükûdan daha fazla eğ\n• Oturarak\n\n**4. KONUŞAMAMA:**\n• Dilsiz\n• Ses çıkaramama\n\n**Hüküm:**\n• Kalben oku\n• Dudak kıpırdat\n• Yeter\n\n**5. KANsayMAZSA:**\n• Yaravelar\n• Şehri\n• İlaç kullanımı\n\n**Hüküm:**\n• Mesh yap (sargı üzerine)\n• Teyemmüm (gerekirse)\n• Olduğu gibi kıl\n\n**NAMAZ ŞILLER:**\n\n**EN İDEAL:**\nAyakta → Rükû → Secde\n\n**SEVİYE 1:**\nAyakta → Oturarak rükû → Secde\n\n**SEVİYE 2:**\nOturarak → Rükû işareti → Secde\n\n**SEVİYE 3:**\nOturarak → İşaretle rükû → İşaretle secde\n\n**SEVİYE 4:**\nYatarak → Sağ yan → İşaretle\n\n**SEVİYE 5:**\nYatarak → Sırtüstü → İşaretle\n\n**SEVİYE 6:**\nKalben niyet → Okuyamıyorsa bile niyet\n\n**SANDALYEDE NAMAZ:**\n• Camide sandalye kullanılabilir\n• Ayakta duramıyorsa\n• Rükû-secde mümkünse yere in\n• Değilse sandalyede eğil\n\n**YATAKTA NAMAZ:**\n• Hasta yatağında\n• Sağ yana yat (kıbleye)\n• İşaretle kıl\n• Olamazsa sırtüstü\n• Başla işaret\n\n**GÖZ İŞARETİ:**\n• Hiçbir uzuv kımıldamazsa\n• Gözle işaret\n• Kalben niyet\n• Allah kabul eder\n\n**TEMİZLİK:**\n• Su kullanamıyorsa → Teyemmüm\n• Teyemmüm de yapamazsa → Olduğu gibi kıl\n• Zaruret kolaylaştırır\n\n**VAKIT:**\n• Vakit çıkmadan kılmalı\n• En hafif şekliyle olsa da\n• Namaz asla terk edilmez\n\n**CEMAAT:**\n• Özürlü cemaatle kılabilir\n• Arkada durmalı\n• Rahatsız etmemeli\n\n**HZ. PEYGAMBER:**\n'Ayakta namaz kıl. Gücün yetmezse oturarak. O da olmazsa yan yatarak.'\n\n**SONUÇ:**\nHiçbir özür namaz kılmamayı gerektirmez. Her halde imkân ölçüsünde namaz kılınır.",
        "source": "Diyanet İşleri Başkanlığı"
    }
]
