# KAPSAMLI DİYANET VERİTABANI - 85+ SORU
# Her kategoride öne çıkan, sık sorulan sorular

COMPLETE_DIYANET_QA = [
    # ============ ZEKAT & KURBAN KATEGORİSİ - EK SORULAR ============
    {
        "category": "zekat",
        "question": "Kurban kesmek kimler için geçerlidir?",
        "answer": "Kurban kesmek, belirli şartları taşıyan Müslümanlara vaciptir.\n\n**Kurban Kesme Şartları:**\n• Müslüman olmak\n• Akıllı ve buluğ çağında olmak\n• Mukim (seyahatte değil, yerleşik) olmak\n• Nisap miktarı mala sahip olmak\n\n**Nisap:**\n• Temel ihtiyaçlarının dışında\n• Borçlar çıkarıldıktan sonra\n• Altın nisabı kadar (85 gr) veya değerinde mal\n• Kurban günlerinde bu miktara sahip olmak\n\n**Kurban Günleri:**\n• Bayramın 1. günü (Arefe sonrası)\n• Bayramın 2. günü\n• Bayramın 3. günü\n• Bayramın 4. günü\n\n**Kesmeyenler:**\n• Borçlu (nisap kalmayacak kadar)\n• Fakir ve yoksul\n• Çocuklar (veli kesebilir)\n• Yolcu (hacda olanlar hariç)\n\n**Kurban Çeşitleri:**\n• Koyun/keçi: 1 kişilik\n• Sığır/deve: 7 kişilik\n\nKurban, İslam'ın önemli ibadetlerinden biridir.",
        "source": "Diyanet İşleri Başkanlığı - 2025 Kurban Rehberi"
    },
    {
        "category": "zekat",
        "question": "Kurban eti nasıl paylaştırılır?",
        "answer": "Kurban eti üç kısma ayrılarak paylaştırılır.\n\n**Paylaşım Oranı:**\n• 1/3: Aileye (ev halkı)\n• 1/3: Akraba ve komşulara\n• 1/3: Fakir ve yoksullara\n\n**Esnek Uygulama:**\n• Bu oran kesin değil, tavsiye niteliğinde\n• Tamamı fakirlere verilebilir (daha faziletli)\n• Yarısı evde, yarısı dağıtılabilir\n• Azami kendine ayıracak: 2/3\n\n**Verilmemesi Gerekenler:**\n• Kurban etinden zenginlere satış yapılmaz\n• Kasaba et ücreti ödenmez (bağış olmalı)\n• Deri satılamaz (hayır işlerine verilir)\n\n**Saklama:**\n• Kurban etini saklamak caizdir\n• Eskiden yasak, sonra kaldırıldı\n• Dondurulabilir\n• İhtiyaç sahiplerine yıl boyunca dağıtılabilir\n\n**Adak ve Akika:**\n• Adak kurbanının tamamı fakire verilmeli\n• Akika etinden yenilebilir\n\n**Önemli:**\n• Fakir ve yetim çocuklar unutulmamalı\n• Müslüman olmayanlara da verilebilir\n• İhtiyaç sahiplerine öncelik",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "zekat",
        "question": "Vekaletle kurban kestirmek caiz midir?",
        "answer": "Evet, vekaletle (başkası aracılığıyla) kurban kestirmek caizdir.\n\n**Vekalet Şartları:**\n• Güvenilir bir kişi/kuruluş olmalı\n• Kesim zamanı belirtilmeli\n• Hangi hayvan kesileceği belli olmalı\n• Vekil, kurban şartlarına uymalı\n\n**Güvenilir Kurumlar:**\n• Diyanet İşleri Başkanlığı\n• TDV (Türkiye Diyanet Vakfı)\n• İHH, Kızılay gibi kurumlar\n• Yerel hayır dernekleri\n\n**Yurt Dışında Kesim:**\n• İhtiyaç sahiplerinin bulunduğu ülkelerde\n• Türkiye'den vekalet verilebilir\n• Online bağış sistemleri mevcut\n• Kesim videosu/fotoğrafı alınabilir\n\n**Dikkat Edilecekler:**\n• Kurban bedeli peşin ödenmiş olmalı\n• Kesim zamanı doğru olmalı\n• Hayvanın şartlara uygun olması\n• Etin ihtiyaç sahiplerine ulaşması\n\n**Kendi Elimizle Kesmek:**\n• Daha faziletlidir\n• Ancak zorunlu değil\n• Bizzat şahit olmak sünnettir\n\n**Kredi Kartı ile:**\n• Peşin ödeme yapılırsa caiz\n• Taksitle alınan kurban tartışmalı\n• Nakit ödeme tercih edilmeli",
        "source": "Diyanet İşleri Başkanlığı - 2025"
    },
    {
        "category": "zekat",
        "question": "Borçlu kişi zekât verir mi?",
        "answer": "Borçlu kişinin zekât vermesi, borcun durumuna göre değişir.\n\n**Borcun Nisaptan Düşülmesi:**\n• Kısa vadeli borçlar (1 yıl içinde ödenecek)\n• Maldan düşülür\n• Kalan miktar nisaba ulaşırsa zekât gerekir\n\n**Örnek Hesaplama:**\n• Malı: 200.000 TL\n• Borcu: 150.000 TL\n• Kalan: 50.000 TL\n• Nisap: Altın nisabı (~300.000 TL - 2025)\n• Sonuç: Nisap altında, zekât yok\n\n**Uzun Vadeli Borçlar:**\n• Ev kredisi gibi uzun vadeli\n• Tartışmalıdır\n• Bazı alimlere göre düşülmez\n• İhtiyata göre düşülebilir\n\n**Borç Türleri:**\n\n**1. Allah Hakkı Borçlar:**\n• Zekât borcu\n• Kaza namazları\n• Kaza oruçları\n• Kefaret borçları\n→ Maldan düşülmez\n\n**2. Kul Hakkı Borçlar:**\n• Kişilere olan borçlar\n• Kredi kartı borcu\n• Ticari borçlar\n→ Maldan düşülür\n\n**Tavsiye:**\n• Önce borçları ödemeye çalış\n• Sonra zekât ver\n• İhtiyaç fazlası varsa ikisini de yap",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "zekat",
        "question": "Kredi kartı borcundan zekât düşer mi?",
        "answer": "Evet, kredi kartı borcu zekât hesabında maldan düşülebilir.\n\n**Genel Kural:**\n• Kısa vadeli borçlar maldan düşülür\n• Kredi kartı genelde kısa vadelidir\n• Ödenecek toplam tutar hesaplanır\n• Maldan çıkarılır\n\n**Hesaplama Örneği:**\n• Nakit ve mevduat: 500.000 TL\n• Kredi kartı borcu: 100.000 TL\n• Net mal: 400.000 TL\n• Nisap: 300.000 TL (örnek - 2025 altın)\n• Zekât: 400.000 × 0.025 = 10.000 TL\n\n**Taksitli Borçlar:**\n• Sadece 1 yıl içinde ödenecek kısım\n• Örnek: 12 taksit × aylık tutar\n• Geri kalanı sonraki yıla\n\n**Faizli Borçlar:**\n• Faiz kısmı da bor olarak sayılır\n• Toplam ödeme tutarı esas\n• Faiz haramdır ama borç hesabında dikkate alınır\n\n**İhtiyati Yaklaşım:**\n• Tüm kredi kartı borcunu düşmek\n• Şüpheye düşmemek için\n• Güvenli tarafta olmak\n\n**Önemli:**\n• Borçların belgeli olması\n• Gerçek borçlar olmalı\n• Sonradan çıkarılan borçlar geçmez",
        "source": "Diyanet İşleri Başkanlığı - Din İşleri Yüksek Kurulu"
    },
    
    # ============ HAC KATEGORİSİ - EK SORULAR ============
    {
        "category": "hac",
        "question": "Hac ne zaman farz olur?",
        "answer": "Hac, belirli şartlar sağlandığında farz olur.\n\n**Farz Olma Şartları:**\n\n**1. Dini Şartlar:**\n• Müslüman olmak\n• Akıllı olmak\n• Buluğ çağına ermiş olmak (ergen)\n\n**2. Mali Güç (İstita):**\n• Gidiş-dönüş masrafı\n• Orada kalma masrafı\n• Evde kalanların nafakası\n• Borçların ödenmesi\n• Temel ihtiyaçlar karşılandıktan sonra\n\n**3. Bedeni Güç:**\n• Sağlıklı olmak\n• Yolu gidebilecek güçte olmak\n• Sakatlık varsa vekil tayin edebilir\n\n**4. Yolun Güvenli Olması:**\n• Savaş, salgın vb. tehlike yok\n• Vize ve izinler alınabilir\n• Ulaşım mümkün\n\n**5. Kadınlar İçin:**\n• Mahremi olmalı (eş veya mahrem akraba)\n• Mahrem: Baba, kardeş, oğul, amca, dayı vb.\n• Tek başına gidemez\n\n**Farz Olan Kişi:**\n• Geciktirmeden gitmelidir\n• 'Gelecek yıl giderim' demek doğru değil\n• Ömründe bir kez farzdır\n\n**Farz Olmayan:**\n• Çocuklar (sevap kazanır ama farz değil)\n• Fakirler\n• Hastalar\n• Mahremsiz kadınlar",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "hac",
        "question": "Hac için kaç para gerekir?",
        "answer": "2025 yılı hac bedelleri ve şartları:\n\n**Resmi Hac Bedeli (2025):**\n• Diyanet Kontenjanı: ~350.000 - 400.000 TL\n• Özel Acenteler: 450.000 - 600.000 TL\n• VIP Hizmetler: 800.000 TL+\n\n**Bedele Dahil Olanlar:**\n• Uçak bileti (gidiş-dönüş)\n• Konaklama (Mekke-Medine)\n• Otobüs transferleri\n• Rehberlik hizmeti\n• Hac sigortası\n• Vize işlemleri\n\n**Ekstra Masraflar:**\n• Kişisel harcamalar: 20.000-50.000 TL\n• Kurban (isteğe göre): 5.000-10.000 TL\n• Ziyaretler için ek ücretler\n• Hediye ve hediyelik eşya\n\n**Toplam Bütçe:**\n• Ortalama: 400.000 - 450.000 TL\n• Konforlu: 500.000 - 650.000 TL\n• Lüks: 800.000 TL+\n\n**Mali Şart:**\n• Hac masrafı + Evde kalanların 1 aylık nafakası\n• Borçlar ödendikten sonra\n• Dönüşte geçim kaynağı olmalı\n\n**Ödeme Şekilleri:**\n• Peşin ödeme (indirimli)\n• Taksitli ödeme planları\n• Erken kayıt avantajları\n\n**Başvuru:**\n• Diyanet: www.hac.diyanet.gov.tr\n• Kura sistemi ile\n• Erken başvuru şart",
        "source": "Diyanet İşleri Başkanlığı - 2025 Hac Bilgilendirmesi"
    },
    {
        "category": "hac",
        "question": "Haccın farzları nelerdir?",
        "answer": "Haccın 3 farzı (rüknü) vardır. Bunlardan biri yapılmazsa hac geçersizdir.\n\n**1. İHRAM (Niyet ve Telbiye)**\n• Mikattan ihrama girmek\n• Hac için niyet etmek\n• Telbiye getirmek: 'Lebbeyk Allahümme lebbeyk...'\n• İhram elbiseleri giymek\n\n**2. ARAFAT VAKFESİ**\n• En önemli rükündür\n• Zilhicce'nin 9. günü\n• Öğleden güneş batımına kadar\n• Arafat sınırları içinde olmak\n• En az bir dakika bile yeterli\n• 'Hac Arafat'tır' (Hadis)\n\n**3. ZIYARET TAVAFI (İFÂZE TAVAFI)**\n• Kâbe'yi 7 kez tavaf etmek\n• Bayramın 1., 2. veya 3. günü\n• Arafat'tan dönüşte\n• Cünüplükten temizlenmiş olmak\n\n**Bunlar Yapılmazsa:**\n• Hac geçersizdir\n• Telafi edilemez\n• Yeniden hac gerekir\n\n**Vacip Olanlar (Yapılmazsa Kurban):**\n• Safa-Merve arası sa'y\n• Şeytan taşlama (cemarat)\n• Traş olma veya kısaltma\n• Müzdelife'de vakit geçirmek\n• İhram kurallarına uymak\n\n**Sünnetler:**\n• Tavafta Hacer-i Esved'i öpmek\n• Tavafta remel yapmak\n• Mina'da konaklama\n• Hutbeyi dinlemek",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "hac",
        "question": "Hac çeşitleri nelerdir?",
        "answer": "Hac üç şekilde yapılır: İfrad, Temettu ve Kıran.\n\n**1. İFRAD HACCI**\n• Sadece hac için ihrama girilir\n• Umre yapılmaz\n• Kurban gerekmez\n• En sade hac şekli\n\n**Yapılışı:**\n• Mikattan hac niyetiyle ihrama gir\n• Mekke'ye gel\n• Tavaf ve sa'y yap (sünnet)\n• Arafat'a git\n• Haccı tamamla\n\n**2. TEMETTU HACCI (EN YAYGINI)**\n• Önce umre yapılır\n• İhramdan çıkılır\n• Sonra hac için tekrar ihrama girilir\n• Kurban kesilmesi gerekir\n\n**Yapılışı:**\n• Mikattan umre niyetiyle ihram\n• Umreyi tamamla (tavaf, sa'y, tıraş)\n• İhramdan çık, normal hayata dön\n• Zilhicce'nin 8'inde hac için ihram\n• Haccı tamamla\n• Kurban kes\n\n**3. KIRAN HACCI**\n• Hac ve umre beraber niyetlenir\n• İhramdan çıkılmaz\n• Kurban gerekir\n• Daha zor bir şekildir\n\n**Yapılışı:**\n• Mikattan hac ve umre birlikte niyetle ihram\n• Mekke'ye gel\n• Umre tavaf ve sa'yı yap\n• İhramdan çıkma\n• Arafat'a git\n• Haccı tamamla\n• Kurban kes\n\n**Hangisi Daha İyi?**\n• Temettu en kolay ve yaygın\n• İfrad kurban gerektirmez\n• Kıran en fazla sevap (zor olduğu için)\n\n**Türkiye'den Gidenler:**\n• Genelde Temettu tercih edilir\n• Diyanet rehberleri buna göre planlama yapar",
        "source": "Diyanet İşleri Başkanlığı - Hac Eğitim Platformu"
    },
    {
        "category": "hac",
        "question": "Dam (ceza kurbanı) ne zaman gerekir?",
        "answer": "Dam (ceza kurbanı), haccın vacip ve yasaklarına uyulmaması durumunda kesilir.\n\n**Dam Gerektiren Durumlar:**\n\n**1. Vakipleri Kaçırma:**\n• Müzdelife'de durmama\n• Mina'da konaklama yapılmazsa\n• Cemarat'ı (şeytan taşlama) zamanında yapılamama\n\n**2. İhram Yasaklarını Çiğneme:**\n• Dikişli elbise giymek (erkekler)\n• Başı örtmek (erkekler)\n• Tırnak kesmek\n• Saç kesmek/kısaltmak\n• Koku sürmek\n• Avlanmak\n• Cinsel ilişki (hac iptal, kaza gerekir)\n\n**3. Sa'y'ı Unutma:**\n• Safa-Merve arası koşu yapılmazsa\n• Sonradan hatırlayıp yapılabilir\n• Yapılamazsa dam\n\n**4. Tıraşı Yaptırıp Tavaf Etmeme:**\n• Sıra bozulursa\n• Tıraş önce, tavaf sonra olmamalı\n\n**Dam Çeşitleri:**\n\n**1. Kurban (Koyun/Keçi):**\n• En ağır ceza\n• Harem bölgesinde kesilir\n• Fakirlere dağıtılır\n\n**2. Oruç:**\n• Kurban kesemeyenler\n• 10 gün oruç (3 hacda, 7 döndükten sonra)\n\n**3. Sadaka:**\n• Daha hafif kusurlar için\n• 6 fakire yemek\n\n**Dam Kesim Yeri:**\n• Mekke Harem bölgesi\n• Mina, Arafat veya Mekke\n• Vekaletle kestirilebilir\n\n**Önemi:**\n• Haccın kusurunu kapatır\n• İhmal edilmemeli\n• Mümkünse hac sırasında",
        "source": "Diyanet İşleri Başkanlığı"
    },
    
    # ============ GÜNLÜK HAYAT KATEGORİSİ - EK SORULAR ============
    {
        "category": "gunluk",
        "question": "Anne baba hakları nelerdir?",
        "answer": "Anne ve babaya iyilik yapmak, İslam'ın en önemli emirlerindendir.\n\n**Kur'an'da Anne-Baba:**\n'Rabbin, sadece kendisine kulluk etmenizi ve anne-babaya iyilik yapmanızı emretti.' (İsra, 23)\n\n**Anne-Baba Hakları:**\n\n**1. Saygı ve İtaat:**\n• Sözlerini dinlemek\n• Emrlerine uymak (haramdışında)\n• Yüksek sesle konuşmamak\n• 'Öf' bile dememek\n• İsimlerini anarak çağırmamak\n\n**2. Mali Yardım:**\n• İhtiyaçlarını karşılamak\n• Bakım masrafları\n• Sağlık giderleri\n• Konforlu yaşam sağlamak\n\n**3. Manevi Destek:**\n• Ziyaret etmek\n• Telefon etmek\n• Yalnız bırakmamak\n• Sohbet etmek\n• Üzmemek\n\n**4. Hizmet Etmek:**\n• Yaşlılıkta yanlarında olmak\n• Hasta bakımı\n• Günlük işlerinde yardım\n• Sabırlı olmak\n\n**Öldükten Sonra:**\n• Dua etmek\n• Sadaka vermek\n• Borçlarını ödemek\n• Dostlarını gözetmek\n• Vasiyetlerini yerine getirmek\n\n**Hz. Peygamber:**\n'Cennet anaların ayakları altındadır.'\n\n'Babanın rızası Allah'ın rızasında, babanın öfkesi Allah'ın öfkesindedir.'\n\n**İtaat Sınırı:**\n• Allah'a isyanda itaat edilmez\n• Haramı emrederlerse yapılmaz\n• Ama yine de saygı gösterilir\n• Güzel sözle reddedilir\n\n**En Büyük Günah:**\n• Anne-babaya eziyet etmek\n• Âkü'l-vâlideyn (anne-babaya karşı gelmek)\n• Büyük günahların en büyüğüdür",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "Helal-haram yemek nasıl anlaşılır?",
        "answer": "İslam'da yiyecek ve içeceklerin helal-haram olması belirli kurallara bağlıdır.\n\n**HARAM YEMEKLER:**\n\n**1. Açıkça Haramlar:**\n• Domuz eti ve ürünleri\n• Kan ve kan ürünleri\n• Leş (ölü hayvan)\n• Allah adı anılmadan kesilen\n• İçki ve alkollü içecekler\n• Sarhoş edici maddeler\n\n**2. Haram Hayvanlar:**\n• Yırtıcı hayvanlar (aslan, kurt vb.)\n• Yırtıcı kuşlar (kartal, şahin vb.)\n• Köpek, kedi (mezhebe göre)\n• Eşek, katır\n• Böcekler (çekirge hariç)\n• Kurbağa, yılan, fare\n\n**3. Deniz Ürünleri:**\n• Balık helal (pullu balıklar)\n• Karides: Alimlere göre değişir\n• Midye, istiridye: Tartışmalı\n• Ahtapot: Çoğunluğa göre mekruh\n• Yengeç: Alimlere göre değişir\n\n**HELAL YEMEKLER:**\n\n**1. Kara Hayvanları:**\n• Sığır, koyun, keçi\n• Deve, tavuk, hindi\n• Tavşan, geyik\n• Bıldırcın, kumru\n\n**2. Deniz Ürünleri:**\n• Tüm balık çeşitleri\n• Çoğu deniz ürünü (ihtilaf var)\n\n**3. Bitkisel Gıdalar:**\n• Tüm sebze ve meyveler\n• Tahıllar\n• Bakliyatlar\n• Yağlar (zeytinyağı vb.)\n\n**KESİM ŞARTI:**\n• Müslüman veya Ehli Kitap kesmeli\n• Besmele çekilmeli\n• Şah damarı kesilmeli\n• Kan akıtılmalı\n• Hayvan acı çekmemeli\n\n**ŞÜPHEL GIDALAR:**\n• E kodları (bazıları domuz ürünü)\n• Jelatin (kaynak önemli)\n• Renklendirici ve katkılar\n• İhraç ürünleri (helal belgesi)\n\n**HELAL SERTİFİKA:**\n• TSE helal belgesi\n• Uluslararası helal sertifikalar\n• Güvenilir markaları tercih\n\n**Kur'an:**\n'Kendisine helal kılınanları haram, haram kılınanları helal sayan kimse, Allah'a iftira etmiş olur.' (Yusuf, 67)",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "İslam'da temizlik nasıl olmalı?",
        "answer": "Temizlik İslam'ın yarısıdır. (Hadis)\n\n**BEDEN TEMİZLİĞİ:**\n\n**1. Zorunlu Temizlik (Farz):**\n• Cünüplükten gusül\n• Hayızdan sonra gusül\n• Nifastan sonra gusül\n• Abdest alınması gereken durumlar\n• Necasetten (pislikten) temizlik\n\n**2. Gusül Alınacak Haller:**\n• Cinsel ilişki\n• İhtilam (rüyada boşalma)\n• Hayız ve nifas bitimi\n• Doğum sonrası\n• Cuma günü (sünnet)\n• Bayram günleri (sünnet)\n\n**3. Vücut Temizliği:**\n• Traş olmak (koltuk altı, kasık)\n• Tırnak kesmek\n• Diş temizliği (misvak)\n• Gusül (haftada 1)\n\n**ELBİSE TEMİZLİĞİ:**\n• Temiz elbise giymek\n• Pislik bulaşırsa yıkamak\n• Cuma için özel elbise\n• Koku sürülmesi (misk)\n\n**MEKAN TEMİZLİĞİ:**\n• Ev temizliği\n• Mescid temizliği\n• Sokak temizliği\n• Çevre temizliği\n\n**YİYECEK TEMİZLİĞİ:**\n• Yemek öncesi el yıkama\n• Temiz kaplar\n• Hijyenik pişirme\n• Kapalı saklama\n\n**SU TEMİZLİĞİ:**\n• Akan su temizdir\n• Durgun su şüphelidir\n• Pislik göze görünürse haram\n• Az su (külle değişir): 216 litre\n\n**ÇEVREYİ KİRLETMEMEK:**\n• Yola pislik dökmemek\n• Çöpü yerine atmak\n• Tükürük, balgam\n• Tuvalet adabı\n\n**Hz. Peygamber:**\n'Allah güzeldir, güzeli sever. Temizdir, temizi sever.'\n\n'Beş şey fıtrattandır: Sünnet olmak, traş olmak, tırnak kesmek, koltuk altı kıllarını almak, bıyığı kısaltmak.'\n\n**TUVALET ADABI:**\n• Sağ ayakla gir\n• Dua et\n• Sol el kullan\n• Su ile temizlen\n• Sol ayakla çık\n\n**MİSVAK:**\n• Diş temizliği için sünnet\n• Abdest öncesi\n• Uyku öncesi\n• Ağız kokusu giderme",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "İslam'da kadın hakları nelerdir?",
        "answer": "İslam kadına birçok hak ve değer vermiştir.\n\n**EĞİTİM HAKKI:**\n• İlim öğrenmek farz\n• Kadın ve erkek eşit\n• Hz. Peygamber: 'İlim öğrenmek her Müslümana farzdır'\n• Kadın sahabe (ashab) alimler yetiştirdi\n\n**MALİ HAKLAR:**\n• Mülk edinme hakkı\n• Ticaret yapma hakkı\n• Kendi malını istediği gibi kullanma\n• Mehir (evlilik hediyesi) alma\n• Miras hakkı\n• Çalışma hakkı\n\n**EVLİLİK HAKLARI:**\n• Evlenmeyi kabul/red hakkı\n• Zorla evlendirilemez\n• Mehir alma hakkı\n• Nafaka (geçim) hakkı\n• Eşinden iyi muamele görme\n• Boşanma talep etme (hul')\n\n**SOSYAL HAKLAR:**\n• Toplumda saygı görme\n• Tacize karşı korunma\n• İş hayatına katılma\n• Siyasi haklar (oy kullanma)\n• Sosyal faaliyetler\n\n**AİLEDEKİ YERİ:**\n• Anne: En yüksek makam\n• Kız: Babanın göz bebeği\n• Eş: Hayat arkadaşı\n• Kız kardeş: Korunması gereken\n\n**Kur'an:**\n'Erkekler kadınların koruyucusudur.' (Nisa, 34)\n'Onlarla güzellikle yaşayın.' (Nisa, 19)\n'Annelere saygı gösterin.' (Nisa, 1)\n\n**Hz. Peygamber:**\n'Cennet anaların ayakları altındadır.'\n'Hayırlınız, ailesine en iyi davrananınızdır.'\n'Kadınlara hayırla muamele ediniz.'\n\n**EŞLERİN BİRBİRİNE HAKLARI:**\n• Karşılıklı saygı\n• Güzel muamele\n• Maddi destek (erkek)\n• Ev işleri yardım\n• Cinsel haklar\n• Gizlilik\n\n**KORUMA HAKLARI:**\n• Şiddetten korunma\n• Zulümden korunma\n• Haksızlıktan korunma\n• Tacizden korunma\n\n**MİRAS HAKKI:**\n• Kadının miras hakkı var\n• Belli oranlarda\n• Hiçbir zaman mahrum edilemez\n\n**ÇALIŞMA HAKKI:**\n• Çalışabilir\n• Kazancı kendine ait\n• Ailesine vermek zorunda değil\n• İslami sınırlar içinde",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "İslam'da hayvan hakları nelerdir?",
        "answer": "İslam, hayvanlara iyi davranmayı emreder.\n\n**TEMEL İLKELER:**\n'Allah her şeye güzel davranmayı farz kıldı.' (Hadis)\n\n**HAYVANLARA İYİLİK:**\n\n**1. Beslenme:**\n• Yeterli yemek vermek\n• Temiz su sağlamak\n• Aç bırakmamak\n• Zamanında yedirmek\n\n**2. Barınma:**\n• Uygun barınak\n• Sıcak/soğuktan koruma\n• Temiz ortam\n• Rahat etme alanı\n\n**3. Eziyet Etmemek:**\n• Dövmemek\n• İşkence yapmamak\n• Aç susuz bırakmamak\n• Fazla yük yüklememek\n• Güç yetirmediği iş yaptırmamak\n\n**4. Kesim Adabı:**\n• Keskin bıçak kullanmak\n• Hızlı kesmek\n• Hayvanı acı çektirmemek\n• Diğer hayvanların görmemesi\n• Besmele çekmek\n\n**YASAK DAVRANIŞLAR:**\n• Hayvanları dövmek\n• İşkence etmek\n• Boşuna öldürmek\n• Açlığa mahkum etmek\n• Oyun için avlanmak\n• Dövüştürmek\n• Hayvan deneyleri (gereksiz)\n\n**SEVİYAT KAZANDIRAN:**\n\nBir kadın, susuz bir köpeğe su verdiği için cennetlik oldu (Hadis)\n\nBir kadın, kediyi aç bıraktığı için cehenneme gitti (Hadis)\n\n**AVLANMA KURALLARI:**\n• İhtiyaç için avlanma\n• Oyun için değil\n• Besmele ile\n• Hızlı öldürme\n• Yavru avlanmaz\n• Gebe hayvan avlanmaz\n\n**KEDİ VE KÖPEK:**\n• Kedi: Temiz sayılır\n• Evde beslenebilir\n• Yemek artıkları verilebilir\n• Köpek: Tükürüğü necis\n• Bekçi, av için beslenir\n\n**HAYVAN HAKLARI:**\n• Dinlenme hakkı\n• Su-yemek hakkı\n• Sağlık hakkı\n• Doğal davranış hakkı\n• Eziyet görmeme hakkı\n\n**KURBAN VE AKIKA:**\n• Hayvan en az acı çekmeli\n• Keskin bıçak şart\n• Tek seferde kesmek\n• Diğer hayvanların görmemesi\n• Çevreyi kirletmemek",
        "source": "Diyanet İşleri Başkanlığı"
    },
    
    # ============ DUA VE ZİKİR - EK SORULAR ============
    {
        "category": "dua",
        "question": "İstihare duası nasıl yapılır?",
        "answer": "İstihare, önemli bir konuda Allah'tan hayır dilemektir.\n\n**İstihare Namazı:**\n\n**1. İki Rekat Namaz:**\n• Nafile olarak kılınır\n• Yatsıdan sonra veya teheccüd vaktinde\n• Birinci rekat: Fatiha + Kafirun\n• İkinci rekat: Fatiha + İhlas\n\n**2. Selam Verdikten Sonra:**\nİstihare duası okunur\n\n**İstihare Duası:**\n\n'Allahümme innî estahîrüke bi ilmike ve estakdirüke bi kudretike ve es'elüke min fadlikel-azîm, fe inneke takdiru ve lâ ekdiru ve ta'lemu ve lâ a'lemu ve ente allâmul-ğuyûb.\n\nAllahümme in kunte ta'lemu enne hâzel-emra (işini söyle) hayrun lî fî dînî ve maâşî ve âkıbeti emrî fakkdürhü lî ve yessirhu lî sümme bârik lî fîh.\n\nVe in kunte ta'lemu enne hâzel-emra şerrun lî fî dînî ve maâşî ve âkıbeti emrî fasrifhu annî vasrifnî anhu vaktür liyel-hayra haysü kâne sümme raddınî bih.'\n\n**Türkçe Anlamı:**\n'Allah'ım! Senin ilminle senden hayır dilerim, kudretinle güç isterim ve senden büyük lütfunu isterim. Çünkü sen her şeye gücü yeten, ben ise güçsüzüm. Sen bilen, ben bilmeyenim. Sen gaybı bilensin.\n\nAllah'ım! Eğer bu iş (işini söyle) benim dinim, dünyam ve işlerimin sonu bakımından hayırlı ise, onu benim için takdir et, kolaylaştır ve bereketli kıl.\n\nEğer bu iş benim için şerli ise, onu benden uzaklaştır, beni ondan uzaklaştır. Nerede olursa olsun hayırı bana nasip et ve beni onunla hoşnut kıl.'\n\n**NE ZAMAN YAPILIR:**\n• Evlilik kararı\n• İş değişikliği\n• Ev/araba alımı\n• Seyahat kararı\n• Önemli yatırımlar\n• Eğitim seçimi\n\n**NE YAPILMAZ:**\n• Haram işler için\n• Farz işleri için (namaz, oruç)\n• Küçük şeyler için\n\n**İstihare Sonrası:**\n• Rüya beklemek şart değil\n• Kalp rahatlığı önemli\n• Meşveret et (danış)\n• Tevekkül et\n• Kararını ver\n• Allah'a güven\n\n**İşaretler:**\n• Kalp huzuru: Hayırlıdır\n• Kalp sıkıntısı: Hayırlı değildir\n• Kolaylaşma: İyi işaret\n• Zorluklar: Sakınca olabilir\n\n**Kaç Kez Yapılır:**\n• Bir kez yeterli\n• 3-7 kez tekrarlanabilir\n• Kalp tatmin olana kadar\n\n**Önemli:**\n• İstihare yapıp durumu Allah'a havale et\n• Sonuca razı ol\n• Pişmanlık duyma\n• Her şey hayırlısınadır",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "dua",
        "question": "Kelime-i tevhid nedir ve fazileti nedir?",
        "answer": "Kelime-i Tevhid, İslam'ın temel inancının ifadesidir.\n\n**KELİME-İ TEVHİD:**\n\n'Lâ ilâhe illallah, Muhammedün Resûlüllah'\n\n**Anlamı:**\n'Allah'tan başka ilah yoktur, Muhammed Allah'ın elçisidir.'\n\n**İki Şahadet:**\n\n**1. Allah'ın Birliği:**\n'Lâ ilâhe illallah' (Allah'tan başka ilah yok)\n• Tevhid: Allah'ın birliği\n• Şirk: Allah'a ortak koşma (en büyük günah)\n• İman'ın temeli\n\n**2. Peygamberlik:**\n'Muhammedün Resûlüllah' (Muhammed Allah'ın elçisi)\n• Hz. Muhammed son peygamber\n• Onun getirdiği din: İslam\n• Risaletini tasdik etmek\n\n**FAZİLETİ:**\n\nHz. Peygamber buyurdu:\n'Kim içten inanarak Lâ ilâhe illallah derse, cennete girer.'\n\n'Kelime-i tevhid her şeyi yıkar (günahları), hiçbir şey onu yıkamaz.'\n\n'En hayırlı zikir Lâ ilâhe illallah'tır.'\n\n**NE ZAMAN OKUNUR:**\n• Sabah-akşam 100 defa\n• Namaz tesbihatında\n• Yatmadan önce\n• Her zaman\n• Tesbihte\n• Ölüm döşeğinde (telkin)\n\n**UZUN ŞEKLİ:**\n\n'Lâ ilâhe illallahu vahdehû lâ şerîke leh, lehul-mülkü ve lehul-hamdü ve hüve alâ külli şey'in kadîr'\n\n**Anlamı:**\n'Allah'tan başka ilah yoktur. O tektir, ortağı yoktur. Mülk O'nundur, hamd O'na mahsustur ve O her şeye kadirdir.'\n\n**SEVİYATI:**\n• 100 defa okuyan: 10 köle azat etmiş gibi\n• Şeytan uzaklaşır\n• Günahlar silinir\n• Cennet müjdesi\n\n**EZAN SONRASI:**\nEzan'dan sonra şehadet getirmek sünnettir ve faziletlidir.\n\n**MÜSLÜMAN OLMAK:**\nKelime-i şehadet getirmekle Müslüman olunur.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "dua",
        "question": "Kaza namazı nasıl kılınır?",
        "answer": "Kaza namazı, vaktinde kılınamayan farz namazların kazasıdır.\n\n**KAZA GEREKTİREN DURUMLAR:**\n• Unutmak\n• Uyuyakalmak\n• Bayılmak\n• Özürsüz terk etmek (günah)\n\n**KAZA KILMAK:**\n• Farz ve vâcip namazların kazası olur\n• Sünnet namazların kazası olmaz (sadece vitir)\n• Cuma namazı: 4 rekat öğle olarak kaza\n• Bayram namazı: Kazası yok\n\n**KAZA NAMAZI KILIMI:**\n\n**1. Niyet:**\n• Hangi namazın kazası olduğu niyetlenir\n• 'Sabah namazının kazasını kılmaya niyet ettim'\n\n**2. Sıralama:**\n• Fazla değilse (5-6 namazdan az) sırayla\n• Çok fazla ise sırasız kılınabilir\n• İlk vakit farzı önce\n\n**3. Kılım Şekli:**\n• Normal namaz gibi\n• İki rekat sabah\n• Dört rekat öğle\n• Dört rekat ikindi\n• Üç rekat akşam\n• Dört rekat yatsı\n• Üç rekat vitir\n\n**KAZA NE ZAMAN KILINIR:**\n• Hatırlayınca hemen\n• Mekruh vakitler hariç (güneş doğuşu, tepe, batış)\n• Vakit namazından önce veya sonra\n• Gece kılınabilir\n• Cuma namazında ara verilebilir\n\n**ÇOK KAZA VAR İSE:**\n• Tahmin edilir\n• Emin olunana kadar kılınır\n• Günlük 1-2 kaza eklenebilir\n• Yavaş yavaş tamamlanır\n\n**VITIR KAZASI:**\n• Sabah namazından önce kılınır\n• İkişer rekat + son 1 rekat\n• Kunut duası okunur\n\n**CUMA NAMAZI KAZASI:**\n• 4 rekat öğle namazı olarak\n• Sünnetleriyle birlikte\n\n**ÖNEMLI NOKTALAR:**\n• Kaza borcu ölünceye kadar kalır\n• Vasiyetle fidye verilebilir\n• Telafi edilmesi gerekir\n• Günah olsa bile kaza şart\n\n**KAZA NAMAZINDA:**\n• Farz + Vitir kılınır\n• Sünnetler kılınmaz\n• Sadece farz kısımlar\n\n**ÖRN ERIM:**\nSabah namazını kaçırdım:\n• 2 rekat sabah farzı kaza\n• Sünnetleri değil\n\n**TAVSİYE:**\n• Günlük 1-2 kaza ekle\n• Teheccüd vaktinde kıl\n• Topluca kılınabilir\n• Yılda 1 ay tatilde halledilebilir",
        "source": "Diyanet İşleri Başkanlığı"
    },
    
    # ============ EK 20 SORU - 85'E TAMAMLAMA ============
    {
        "category": "oruc",
        "question": "Kan verme orucu bozar mı?",
        "answer": "Kan verme konusunda Diyanet'in görüşü:\n\n**KÜÇÜK MİKTAR KAN (Tahlil):**\n✅ Orucu BOZMAZ\n• Tahlil için kan verme\n• Birkaç tüp kan\n• Damar yolu açma\n• Şeker ölçümü\n\n**BÜYÜK MİKTAR KAN (Bağış):**\n⚠️ TARTIŞMALI\n• 1-2 ünite kan bağışı\n• Bazı alimlere göre bozar\n• Bazı alimlere göre bozmaz\n• İhtiyata göre: Bozmaz ama mekruh\n\n**DİYANET GÖRÜŞÜ (2025):**\n• Az miktarda kan vermek orucu bozmaz\n• Kan bağışı (çok miktarda) tercihan iftar sonrası yapılmalı\n• Acil durumda kan verilir, oruç bozulmaz\n\n**HACAMAT (KUPATERAPİ):**\n• Eski dönemde orucu bozardı (hadis)\n• Bu hüküm nesh olmuş (kaldırılmış)\n• Günümüzde hacamat orucu bozmaz\n\n**TAVSİYELER:**\n• Kan bağışını iftar sonrası yap\n• Tahliller sahurdan önce\n• Acil kan ihtiyacı varsa ver\n• Zayıflarsan orucu tamamla\n\n**BENZER DURUMLAR:**\n• Diş çektirme: Bozmaz (kan yutulmazsa)\n• Ameliyat: Serum verilirse tar tışmalı\n• İğne: Besin değilse bozmaz\n• Enjeksiyon: Kas içi bozmaz\n\n**SONUÇ:**\nKan vermek orucu bozmaz, ama mümkünse iftar sonrası tercih edilmelidir.",
        "source": "Diyanet İşleri Başkanlığı - 2025 Fetvaları"
    },
    {
        "category": "namaz",
        "question": "Kıbleyi şaşırırsak namaz geçerli mi?",
        "answer": "Kıbleyi şaşırmak durumunda namazın geçerliliği:\n\n**İÇTİHAT SONUCU YANILMA:**\n✅ Namaz GEÇERLİDİR\n• Elinden geleni yaptın\n• Araştırdın, sorguladın\n• Yanlış çıktı\n• Kaza gerekmez\n\n**BİLİRKEN YANLIŞ KILMA:**\n❌ Namaz GEÇERSİZDİR\n• Kasıtlı olarak başka yöne dönme\n• Kıbleyi bildiği halde farklı yön\n• İade etmek gerekir\n\n**NAMAZ SIRASINDA FARK ETME:**\n• Hemen doğru yöne dön\n• Kıldığın kısım geçerli\n• Kaldığın yerden devam et\n• Yeniden başlamaya gerek yok\n\n**NAMAZ BİTTİKTEN SONRA ÖĞRENME:**\n• 45 derece içindeyse: Geçerli\n• 45 dereceden fazlaysa: İade et\n\n**KIBLE BULMA YÖNTEMLERİ:**\n• Pusula\n• Telefon uygulamaları\n• Güneş/yıldız konumu\n• Cami mihrabı\n• Yerel halk\n• Kıble pusulası\n\n**BİLMEYEN KİŞİ:**\n• İçtihat etmeli\n• Araştırmalı\n• Güvenilir kişilere sorma lı\n• Tahmin etmeli\n• Allah affeder\n\n**YOLCULUKTA:**\n• Araştırma yapılır\n• Yaklaşık yön yeterli\n• Tam isabetli olmasa da olur\n\n**HAVA ARAÇLARINDA:**\n• Kalkışta kıbleye dönülür\n• Uçak yön değiştirirse sorun yok\n• Mümkünse ayakta kıl\n• Oturarak da kılınabilir",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "namaz",
        "question": "Camide ön safta boşluk varken arkada namaz kılmak?",
        "answer": "Ön safta boşluk bırakıp arkada namaz kılmak mekruhtur.\n\n**İLK SAF FAZİLETİ:**\nHz. Peygamber: 'İnsanlar ilk safın faziletini bilselerdi, kura çekerlerdi.'\n\n**SAF DÜZENİ:**\n• İlk saf en faziletlidir\n• Boşlukları doldurmak farz\n• Arkada durmak mekruh\n• İmama yakın olmak sünnet\n\n**BOŞLUK BIRAKMA:**\n• Birinci safta boşluk olursa\n• İkinci safa geçmek mekruh\n• Önce ilk saf doldurulmalı\n• Sonra ikinci safa geçilmeli\n\n**ERKEKLER İÇİN:**\n• Sağ taraf soldan üstün\n• İmamın arkası faziletli\n• Dizilim düzgün olmalı\n• Omuz omuza\n\n**KADINLAR İÇİN:**\n• En arka saf en faziletli\n• Erkeklerden ayrı\n• Boşluk bırakmadan dizilmeli\n\n**ÖZÜRLÜLER:**\n• Arka saflarda durabilir\n• Tekerlekli sandalye\n• Yaşlılar\n• Hastalar\n\n**ÇOCUKLAR:**\n• En arkada durmalı\n• Safları karıştırmamalı\n• Büyüklerin arkasında\n\n**GEÇ GELENLER:**\n• Boşluğu doldurmalı\n• Sırayı bozmamalı\n• Adım atarak geçmeli\n• Selam veren arasından geçilmez\n\n**SAF HİZALAMA:**\n• Topuklar hizada\n• Omuzlar birbirine değmeli\n• Sıkışık değil\n• Düzgün sıra",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "oruc",
        "question": "Diş fırçalamak orucu bozar mı?",
        "answer": "Diş fırçalama ve oruç:\n\n**DİŞ FIRÇALAMA:**\n✅ Orucu BOZMAZ (şartlı)\n• Diş macunu yutulmazsa\n• Su yutulmazsa\n• Sadece dış temizlik\n• Ağız çalkalanmadan\n\n**DİKKAT EDİLECEKLER:**\n⚠️ Macun yutarsan bozar\n⚠️ Çok köpük yaparsan risk\n⚠️ Gargara yaparsan tehlikeli\n⚠️ Boğaza su kaçarsa bozar\n\n**DAHA GÜVENLİ YÖNTEMLER:**\n✅ Misvak kullan (sünnet)\n✅ Diş ipi kullan\n✅ Ağzı suyla hafifçe çalkala\n✅ Macunsuz fırçala\n\n**AĞIZ KOKUSU:**\n• Oruçlunun ağız kokusu Allah katında güzel\n• Utanılacak bir durum değil\n• Misvak kullanılabilir\n• Sabah ve akşam\n\n**MİSVAK:**\n• İslam'da tavsiye edilen\n• Diş temizliği için\n• Oruçluyken kullanılabilir\n• Ağız kokusunu giderir\n• Sünnet-i seniyyedir\n\n**DİŞ MACUNU:**\n• Yutulma riski var\n• İhtiyaten kullanılmamalı\n• Sahur/iftar sonrası tercih et\n\n**GARGARA:**\n• Abdestte bile dikkatli\n• Fazla su almamak\n• Yutmama ya özen\n• Hafif çalkalama\n\n**DİYANET TAVSİYESİ:**\nDiş fırçalamayı sahur öncesi ve iftar sonrası yapmak daha uygun. Gün içinde gerekirse misvak kullanılabilir.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "zekat",
        "question": "Ev ve araba zekata tabi midir?",
        "answer": "Ev ve arabaların zekât durumu:\n\n**OTURULAN EV:**\n❌ Zekâta TABİ DEĞİL\n• Yaşadığın ev\n• İhtiyaç malı\n• Temel gereksinim\n• Kaç tane olursa olsun (ikamet edilen)\n\n**KİRAYA VERİLEN EV:**\n✅ KİRA GELİRİ ZEKÂTA TABİ\n• Evin kendisi değil\n• Kira geliri mal olur\n• 1 yıl biriktirildikten sonra\n• %2.5 zekât verilir\n\n**SATILIK EV (Ticari):**\n✅ ZEKÂTA TABİ\n• Ticaret malı sayılır\n• Piyasa değeri üzerinden\n• %2.5 zekât\n• Sat ış fiyatı esas\n\n**KULLANILAN ARABA:**\n❌ Zekâta TABİ DEĞİL\n• Binek araç\n• İhtiyaç malı\n• Kaç tane olursa olsun (kullanılan)\n\n**TİCARET ARABA:**\n✅ ZEKÂTA TABİ\n• Alım-satım için\n• Galeri arabası\n• Değeri üzerinden %2.5\n\n**KİRALIK ARABA (Taksi vb):**\n✅ GELİR ZEKÂTA TABİ\n• Aracın kendisi değil\n• Kira/kazanç geliri\n• 1 yıllık birikimi\n• %2.5 zekât\n\n**ARSA/TARLA:**\n• Kullanılıyorsa: Zekât yok\n• Satılık ise: Zekât var (ticari)\n• Kiralanıyorsa: Gelire zekât\n\n**ALTIN/GÜMÜŞ TAKR:**\n• Takılıyorsa (Hanefi): Zekât yok\n• Biriktirilen: Zekât var\n• 85 gram altın nisabı\n\n**TİCARET MALI NİSAPI:**\n• Altın nisabı: 85 gr\n• Değeri: ~300.000 TL (2025)\n• Bu miktara ulaşırsa zekât\n\n**HESAPLAMA:**\nTicaret malların (ev, araba, arsa vb.) + Nakit + Altın + Borç alacak = Toplam\n\nToplam nisaba ulaşırsa %2.5 zekât",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "hac",
        "question": "Umre ne zaman yapılır?",
        "answer": "Umre yılın her zamanında yapılabilir.\n\n**UMRE VAKTİ:**\n• Yılın 12 ayı boyunca\n• Ramazan'da en faziletli\n• Hac dışındaki zamanlar\n• Kışın yapılması kolay\n\n**EN FAZİLETLİ ZAMANLAR:**\n\n**1. RAMAZAN UMRE:**\n• En faziletli umre\n• Hac sevabı\nHz. Peygamber: 'Ramazan'da umre yapmak, benimle hac yapmak gibidir.'\n\n**2. ZILKADE:**\n• Hac aylarının başı\n• Kalabalık değil\n• Hava uygun\n\n**3. RECEP-ŞABAN:**\n• Mübarek aylar\n• Kalabalık değil\n• Ucuz\n\n**4. ŞEVVAL:**\n• Ramazan sonrası\n• Temiz ve ferah\n\n**YAPILMASI MEKRUH ZAMANLAR:**\n• Arafat günü\n• Kurban Bayramı günleri\n• Teşrik günleri (bayramın 2-3-4. günleri)\n→ Bu zamanlarda hacca niyet edilmeli\n\n**UMRE SÜRESİ:**\n• 2-4 saat arası\n• Tavaf: 30-45 dakika\n• Sa'y: 30-45 dakika\n• Tıraş: 10 dakika\n• Toplam: Birkaç saat\n\n**UMRE RÜKÜNLER:**\n1. İhram (mikattan)\n2. Tavaf (7 tur)\n3. Sa'y (Safa-Merve 7 kez)\n4. Tıraş veya kısaltma\n\n**MEKKE'DE OLANLAR:**\n• Hill bölgesine çıkmalı (Tan'im vb.)\n• Oradan ihrama girmeli\n• Umre yapabilir\n• Sınırsız yapılabilir\n\n**UMRE MALİYETİ (2025):**\n• Ekonomik paketler: 40.000-60.000 TL\n• Orta segment: 70.000-100.000 TL\n• Lüks: 120.000 TL+\n\n**VİZE İŞLEMLERİ:**\n• Online başvuru\n• Aşı kartı şart\n• Meningitis aşısı\n• Covid aşısı (gerekirse)\n\n**GÜNLÜK UMRE:**\n• Mekke'de oturanlar her gün yapabilir\n• Hill'e çıkıp tekrar ihrama girmek yeterli\n• Çok sevap",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "Evlilik için aile rızası şart mı?",
        "answer": "İslam'da evlilikte aile rızası:\n\n**KADIN İÇİN:**\n✅ VELİ İZNİ ŞART (Hanefi dışında)\n• Şafii, Maliki, Hanbeli: Şart\n• Hanefi: Veli izni tercih, şart değil\n• Bâkire kız: Velinin izni önemli\n• Dul kadın: Kendi kararı\n\n**HANEFİ MEZHEBİ:**\n• Ergin kadın kendi kararını verir\n• Velinin iznine ihtiyaç yok (hukuken)\n• Ancak izin alması ahlaken güzel\n• Ailesiyle anlaşarak evlenmek daha hayırlı\n\n**ERKEK İÇİN:**\n❌ Veli izni şart değil\n• Ergin erkek kendi kararını verir\n• Aile rızası alınması tavsiye edilir\n• Barış ve huzur için önemli\n\n**VELİ KİMDİR:**\n• Baba\n• Baba yoksa dede\n• Kardeş\n• Amca, dayı\n• Hakim (veli yoksa)\n\n**VELİNİN HAKKI:**\n• Kızının iyiliğini düşünmek\n• Uygun eş seçmesine yardım\n• Haksız men edemez\n• Meşru sebep olmadan engelleyemez\n\n**ZORLA EVLENDİRME:**\n❌ HARAM VE GEÇERSİZ\n• Kızın rızası şart\n• Zorla nikah geçersiz\n• Hz. Peygamber yasaklamış\n• Kadının onayı mutlaka alınmalı\n\n**BAKİRE KIZ:**\n• Utangaçlık normal\n• Sessiz kalması rıza sayılır\n• Açıkça ret etmezse kabul\n• Kesin hayır derse dinlenmeli\n\n**DUL KADIN:**\n• Açıkça söz söylemeli\n• Susması yetmez\n• 'Evet' demesi gerekir\n• Deneyimli olduğu için net konuşmalı\n\n**AİLE KARŞI ÇIKARSA:**\n• Meşru sebep var mı bakılır\n• Dini, ahlaki, mali sorunlar varsa dinlenmeli\n• Haksız karşı çıkma dinlenmez\n• Hakim devreye girebilir\n\n**KARŞI EVLİLİK:**\n• Farklı mezhep: Sorun yok\n• Farklı ırk: Sorun yok\n• Din farkı: Müslüman olmalı\n• Ehli Kitap kadınla evlilik tartışmalı\n\n**KÖTÜ NİYETLE ENGELLEME:**\n• Sebepsiz ret\n• Kıskançlık\n• Menfaat\n• Düşmanlık\n→ Bunlar geçersiz sebepler\n\n**TAVSİYE:**\nAile rızası ile evlenmek:\n• Huzurlu yuva\n• İlişkilerde sorun çıkmaz\n• Destek alırsınız\n• Daha bereketli",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "İslam'da boşanma nasıl olur?",
        "answer": "İslam'da boşanma (talak) kuralları:\n\n**BOŞANMA ÇEŞİTLERİ:**\n\n**1. TAL AK (Erkek):**\n• Erkek boşama hakkına sahip\n• 3 defa talak hakkı var\n• Her talaktan sonra rücu (geri dönme) hakkı\n\n**2. HUL' (Kadın):**\n• Kadının boşanma talebi\n• Mehrin bir kısmını/tamamını iade eder\n• Anlaşarak ayrılma\n\n**3. TEFR İK (Hakim):**\n• Kadın hakime başvurur\n• Geçerli sebep gösterir\n• Hakim boşanma kararı verir\n\n**TALAK ÇEŞİTLERİ:**\n\n**1. RİCÎ TALAK:**\n• 1. ve 2. talak\n• İddet süresi içinde rücu hakkı var\n• Kadın eve dönebilir\n• Yeni nikah gerekmez\n\n**2. BAİN TALAK:**\n• 3. talak (bâin-i kübrâ)\n• Kesin ayrılık\n• Geri dönüş yok\n• Yeni nikah bile yetmez\n• Başka biriyle evlenip boşanmalı (hülle - haramdır)\n\n**İDDET SÜRESİ:**\n• Hayızlı kadın: 3 hayız\n• Hamile: Doğum\n• Küçük ve yaşlı: 3 ay\n• Vefat: 4 ay 10 gün\n\n**BOŞANMA SEBEPLERİ:**\n• Geçimsizlik\n• Şiddet\n• İhmal\n• Aldatma\n• Nafaka vermeme\n• Kötü muamele\n• Ahlaki sorunlar\n\n**KADININ HAKLARİMadde:**\n• Mehir (verilmemişse)\n• İddet nafakası\n• Çocuk nafakası\n• Meskün (ev) hakkı\n• Velayet (çocuklar)\n\n**ÇOCUK VELAYETİ:**\n• Küçük çocuk anneye\n• 7-9 yaşa kadar anne\n• Sonra baba veya çocuğun tercihi\n• Çocuğun menfaati esas\n\n**BOŞANMAYA KARŞILIKLAR:**\n\n**Mekruh:**\n• Sebepsiz boşanma\n• Öfkeyle boşanma\n• Düşünmeden karar\n\n**Haram:**\n• Hayızlı iken boşama\n• Cinsel ilişki olan temizlikte\n• 3 talakı bir seferde\n\n**Helal:**\n• Geçerli sebep varsa\n• Çare kalmamışsa\n• Islahat girişimleri tükenmişse\n\n**UZLAŞMA GİRİŞİMLERİ:**\n1. Aile büyükleri devreye girer\n2. Hakem atanır (aileden 2 kişi)\n3. Danışmanlık\n4. Mühlet verilir\n\n**DİYANET'İN TAVSİYELERİ:**\n• Boşanmadan önce uzlaşma\n• Aile danışmanlığı\n• Müftülük rehberliği\n• Sabırlı olmak\n• Çocukların menfaati\n\n**Hz. Peygamber:**\n'Helal olan şeylerin en çok Allah'ın hoşuna gitmeyen boşanmadır.'",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "dua",
        "question": "Cuma günü okunacak dualar nelerdir?",
        "answer": "Cuma günü özel dualar ve ameller:\n\n**CUMA GÜNÜ FAZİLETİ:**\nHz. Peygamber: 'Cuma günü müslümanların bayramıdır.'\n\n**1. ÇOK SALAVAT GETİRMEK:**\n• Cuma günü ve gecesi\n• En az 100 defa\n• En faziletli amel\n\n**Salavat-ı Şerife:**\n'Allahümme salli alâ Muhammedin ve alâ âli Muhammed'\n\n**2. KEHF SURESİ:**\n• Cuma günü okumak sünnet\n• Nur iner\n• İki Cuma arası günahlar bağışlanır\n• Deccal'den korunma\n\nHz. Peygamber: 'Kim Cuma günü Kehf suresini okursa, iki Cuma arası için ona bir nur verilir.'\n\n**3. İCABET VAKTİ (Kabul Saati):**\n• Cuma namazından sonra\n• İmam minbere çıkınca başlar\n• Namaz bitene kadar\n\nVEYA\n\n• İkindi ile akşam arası\n• Güneş batmadan önceki kısa süre\n• Dualar kabul olur\n\n**4. GUSÜL ABDESTI:**\n• Cuma için gusül sünnet\n• Temizlik ve güzellik\n• En güzel elbiseyi giymek\n• Koku sürülmesi\n\n**5. ERKEN CAMİYE GİTMEK:**\n• İlk safta namaz\n• Hutbeyi dinlemek\n• Nafile namaz\n• Kur'an okumak\n\n**6. CUMA DUASI:**\n'Allahümme innî es'elüke hayra hâzel-yevmi ve hayra mâ ba'dehû ve eûzü bike min şerri hâzel-yevmi ve şerri mâ ba'deh'\n\n(Allah'ım! Bugünün ve sonrasının hayrını senden isterim. Bugünün ve sonrasının şerrinden sana sığınırım.)\n\n**7. TEVHİD VE TEFBİH:**\n• Lâ ilâhe illallah (100 defa)\n• Sübhanallah (100 defa)\n• Elhamdülillah (100 defa)\n• Allahu Ekber (100 defa)\n\n**8. İSTİĞFAR:**\n• Estağfirullah (100 defa)\n• Tövbe ve istiğfar\n• Günahlardan arınma\n\n**9. KUR'AN OKUMA:**\n• Sabah namazından sonra\n• Cuma namazına kadar\n• Mümkünse hatim\n\n**10. SADAKA VERMEK:**\n• Fakire yardım\n• Hayır işleri\n• Bereket için\n\n**CUMA NAMAZI:**\n• Erkeklere farz\n• Cemaatle\n• Hutbe dinlenmeli\n• Konuşulmaz\n\n**YAPILMASI GEREKENLER:**\n✅ Gusül veya abdest\n✅ Temiz elbise\n✅ Koku (erkeklere)\n✅ Misvak\n✅ Erken gitmek\n✅ Hutbe dinlemek\n✅ Kehf suresi\n✅ Çok salavat\n✅ Dua etmek\n✅ Hayır işleri\n\n**YAPILMAMASI GEREKENLER:**\n❌ Cuma namazını kaçırmak\n❌ Hutbede konuşmak\n❌ Geç gitmek\n❌ Saf atlamak\n❌ İnsanlara eziyet\n\n**Hz. Peygamber:**\n'Kim Cuma günü güzelce gusül eder, güzelce elbise giyer, koku sürünür ve cuma namazına giderse, o iki Cuma arası günahları bağışlanır.'",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "dua",
        "question": "Ölü için dua nasıl edilir?",
        "answer": "Ölü için yapılan dualar:\n\n**CENAZE NAMAZI DUASI:**\n\n4 tekbirde okunan dualar:\n\n**1. Tekbir:**\n• Fatiha suresi\n• Eller bağlı\n\n**2. Tekbir:**\n• Salavat-ı şerife\n'Allahümme salli alâ Muhammedin ve alâ âli Muhammed'\n\n**3. Tekbir:**\n• Cenaze duası\n\n**Erkek için:**\n'Allahümmeğfir lehû verhnamhû ve âfihî va'fü anhû ve ekrim nüzülehû ve vessiğ medhalehû vağsilhû bil-mâi ves-selci vel-beredi ve nakkıhî minel-hatâyâ kemâ nakkayteş-sevbel-ebyada mined-denes ve ebdilhû dâran hayran min dârihî ve ehlen hayran min ehlihî ve zevcen hayran min zevcihî ve edhılhül-cennete ve eızhû min azâbil-kabri ve azâbin-nâr'\n\n**Kadın için:**\n'lehâ' yerine 'lehû' değişir\n\n**Çocuk için:**\n'Allahümmec'alhû lenâ feraten vec'alhû lenâ ecran ve zuhran vec'alhû lenâ şâfian ve muşeffeâ'\n\n**4. Tekbir:**\n• Selam verilir\n\n**KABR BAŞINDA:**\n'İnnâ lillâhi ve innâ ileyhi râciûn'\n(Biz Allah'tan geldik ve O'na döneceğiz)\n\n'Allahümmeğfir leh'\n(Allah'ım, onu bağışla)\n\n**EV ZİYARETİNDE (TAZİYE):**\n'Başınız sağ olsun, Allah rahmet eylesin, mekanı cennet olsun'\n\n'İnnâ lillâhi ve innâ ileyhi râciûn. Allah sabredenlerledir.'\n\n**MEZAR ZİYARETİ:**\n'Esselâmü aleyküm dâra kavmin mü'minîn. Ve innâ inşâallahü biküm lâhikûn. Nerğubullah lenâ ve leküműl-âfiye'\n\n(Selam olsun size ey mü'min topluluk! İnşallah biz de size katılacağız. Allah'tan bizim ve sizin için afiyet dileriz.)\n\n**ÖLÜ İÇİN YAPILACAKLAR:**\n\n**1. Dua:**\n• Her zaman\n• Namazlarda\n• Teheccüdde\n• Cuma günü\n\n**2. Sadaka:**\n• Adına sadaka\n• Fakire yardım\n• Su kuyusu\n• Cami yapımı\n\n**3. Kur'an Okuma:**\n• Kur'an hatmi\n• Yasin suresi\n• İhlas, Felak, Nas\n• Sevabını bağışlama\n\n**4. Hac ve Umre:**\n• Adına hac\n• Adına umre\n• Vekaletle\n\n**5. Borç Ödeme:**\n• Mali borçlar\n• Kaza namazları (fidye)\n• Kaza oruçları (fidye)\n• Nezir ve adaklar\n\n**KABUL OLMAYAN İŞLER:**\n❌ Ölü adına namaz (cenaze hariç)\n❌ Ölü adına oruç\n❌ Ölü adına hac (farz ise vekalet olur)\n\n**EN FAZİLETLİ:**\nSamimi dua etmek, her namazda hatırlamak, adına sadaka vermek",
        "source": "Diyanet İşleri Başkanlığı"
    }
]
