# KAPSAMLI DİYANET VERİTABANI - 85+ SORU
# Her kategoride öne çıkan, sık sorulan sorular

COMPLETE_DIYANET_QA = [
    # ============ ZEKAT & KURBAN KATEGORİSİ - EK SORULAR ============
    {
        "category": "zekat",
        "question": "Kurban kesmek kimler için geçerlidir?",
        "answer": "Kurban kesmek, belirli şartları taşıyan Müslümanlara vaciptir.\n\n**Kurban Kesme Şartları:**\n• Müslüman olmak\n• Akıllı ve buluğ çağında olmak\n• Mukim (seyahatte değil, yerleşik) olmak\n• Nisap miktarı mala sahip olmak\n\n**Nisap:**\n• Temel ihtiyaçlarının dışında\n• Borçlar çıkarıldıktan sonra\n• Altın nisabı kadar (85 gr) veya değerinde mal\n• Kurban günlerinde bu miktara sahip olmak\n\n**Kurban Günleri:**\n• Bayramın 1. günü (Arefe sonrası)\n• Bayramın 2. günü\n• Bayramın 3. günü\n• Bayramın 4. günü\n\n**Kesmeyenler:**\n• Borçlu (nisap kalmayacak kadar)\n• Fakir ve yoksul\n• Çocuklar (veli kesebilir)\n• Yolcu (hacda olanlar hariç)\n\n**Kurban Çeşitleri:**\n• Koyun/keçi: 1 kişilik\n• Sığır/deve: 7 kişilik\n\nKurban, İslam'ın önemli ibadetlerinden biridir.",
        "source": "Diyanet İşleri Başkanlığı - 2025 Kurban Rehberi"
    },
    {
        "category": "zekat",
        "question": "Kurban eti nasıl paylaştırılır?",
        "answer": "Kurban eti üç kısma ayrılarak paylaştırılır.\n\n**Paylaşım Oranı:**\n• 1/3: Aileye (ev halkı)\n• 1/3: Akraba ve komşulara\n• 1/3: Fakir ve yoksullara\n\n**Esnek Uygulama:**\n• Bu oran kesin değil, tavsiye niteliğinde\n• Tamamı fakirlere verilebilir (daha faziletli)\n• Yarısı evde, yarısı dağıtılabilir\n• Azami kendine ayıracak: 2/3\n\n**Verilmemesi Gerekenler:**\n• Kurban etinden zenginlere satış yapılmaz\n• Kasaba et ücreti ödenmez (bağış olmalı)\n• Deri satılamaz (hayır işlerine verilir)\n\n**Saklama:**\n• Kurban etini saklamak caizdir\n• Eskiden yasak, sonra kaldırıldı\n• Dondurulabilir\n• İhtiyaç sahiplerine yıl boyunca dağıtılabilir\n\n**Adak ve Akika:**\n• Adak kurbanının tamamı fakire verilmeli\n• Akika etinden yenilebilir\n\n**Önemli:**\n• Fakir ve yetim çocuklar unutulmamalı\n• Müslüman olmayanlara da verilebilir\n• İhtiyaç sahiplerine öncelik",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "zekat",
        "question": "Vekaletle kurban kestirmek caiz midir?",
        "answer": "Evet, vekaletle (başkası aracılığıyla) kurban kestirmek caizdir.\n\n**Vekalet Şartları:**\n• Güvenilir bir kişi/kuruluş olmalı\n• Kesim zamanı belirtilmeli\n• Hangi hayvan kesileceği belli olmalı\n• Vekil, kurban şartlarına uymalı\n\n**Güvenilir Kurumlar:**\n• Diyanet İşleri Başkanlığı\n• TDV (Türkiye Diyanet Vakfı)\n• İHH, Kızılay gibi kurumlar\n• Yerel hayır dernekleri\n\n**Yurt Dışında Kesim:**\n• İhtiyaç sahiplerinin bulunduğu ülkelerde\n• Türkiye'den vekalet verilebilir\n• Online bağış sistemleri mevcut\n• Kesim videosu/fotoğrafı alınabilir\n\n**Dikkat Edilecekler:**\n• Kurban bedeli peşin ödenmiş olmalı\n• Kesim zamanı doğru olmalı\n• Hayvanın şartlara uygun olması\n• Etin ihtiyaç sahiplerine ulaşması\n\n**Kendi Elimizle Kesmek:**\n• Daha faziletlidir\n• Ancak zorunlu değil\n• Bizzat şahit olmak sünnettir\n\n**Kredi Kartı ile:**\n• Peşin ödeme yapılırsa caiz\n• Taksitle alınan kurban tartışmalı\n• Nakit ödeme tercih edilmeli",
        "source": "Diyanet İşleri Başkanlığı - 2025"
    },
    {
        "category": "zekat",
        "question": "Borçlu kişi zekât verir mi?",
        "answer": "Borçlu kişinin zekât vermesi, borcun durumuna göre değişir.\n\n**Borcun Nisaptan Düşülmesi:**\n• Kısa vadeli borçlar (1 yıl içinde ödenecek)\n• Maldan düşülür\n• Kalan miktar nisaba ulaşırsa zekât gerekir\n\n**Örnek Hesaplama:**\n• Malı: 200.000 TL\n• Borcu: 150.000 TL\n• Kalan: 50.000 TL\n• Nisap: Altın nisabı (~300.000 TL - 2025)\n• Sonuç: Nisap altında, zekât yok\n\n**Uzun Vadeli Borçlar:**\n• Ev kredisi gibi uzun vadeli\n• Tartışmalıdır\n• Bazı alimlere göre düşülmez\n• İhtiyata göre düşülebilir\n\n**Borç Türleri:**\n\n**1. Allah Hakkı Borçlar:**\n• Zekât borcu\n• Kaza namazları\n• Kaza oruçları\n• Kefaret borçları\n→ Maldan düşülmez\n\n**2. Kul Hakkı Borçlar:**\n• Kişilere olan borçlar\n• Kredi kartı borcu\n• Ticari borçlar\n→ Maldan düşülür\n\n**Tavsiye:**\n• Önce borçları ödemeye çalış\n• Sonra zekât ver\n• İhtiyaç fazlası varsa ikisini de yap",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "zekat",
        "question": "Kredi kartı borcundan zekât düşer mi?",
        "answer": "Evet, kredi kartı borcu zekât hesabında maldan düşülebilir.\n\n**Genel Kural:**\n• Kısa vadeli borçlar maldan düşülür\n• Kredi kartı genelde kısa vadelidir\n• Ödenecek toplam tutar hesaplanır\n• Maldan çıkarılır\n\n**Hesaplama Örneği:**\n• Nakit ve mevduat: 500.000 TL\n• Kredi kartı borcu: 100.000 TL\n• Net mal: 400.000 TL\n• Nisap: 300.000 TL (örnek - 2025 altın)\n• Zekât: 400.000 × 0.025 = 10.000 TL\n\n**Taksitli Borçlar:**\n• Sadece 1 yıl içinde ödenecek kısım\n• Örnek: 12 taksit × aylık tutar\n• Geri kalanı sonraki yıla\n\n**Faizli Borçlar:**\n• Faiz kısmı da bor olarak sayılır\n• Toplam ödeme tutarı esas\n• Faiz haramdır ama borç hesabında dikkate alınır\n\n**İhtiyati Yaklaşım:**\n• Tüm kredi kartı borcunu düşmek\n• Şüpheye düşmemek için\n• Güvenli tarafta olmak\n\n**Önemli:**\n• Borçların belgeli olması\n• Gerçek borçlar olmalı\n• Sonradan çıkarılan borçlar geçmez",
        "source": "Diyanet İşleri Başkanlığı - Din İşleri Yüksek Kurulu"
    },
    
    # ============ HAC KATEGORİSİ - EK SORULAR ============
    {
        "category": "hac",
        "question": "Hac ne zaman farz olur?",
        "answer": "Hac, belirli şartlar sağlandığında farz olur.\n\n**Farz Olma Şartları:**\n\n**1. Dini Şartlar:**\n• Müslüman olmak\n• Akıllı olmak\n• Buluğ çağına ermiş olmak (ergen)\n\n**2. Mali Güç (İstita):**\n• Gidiş-dönüş masrafı\n• Orada kalma masrafı\n• Evde kalanların nafakası\n• Borçların ödenmesi\n• Temel ihtiyaçlar karşılandıktan sonra\n\n**3. Bedeni Güç:**\n• Sağlıklı olmak\n• Yolu gidebilecek güçte olmak\n• Sakatlık varsa vekil tayin edebilir\n\n**4. Yolun Güvenli Olması:**\n• Savaş, salgın vb. tehlike yok\n• Vize ve izinler alınabilir\n• Ulaşım mümkün\n\n**5. Kadınlar İçin:**\n• Mahremi olmalı (eş veya mahrem akraba)\n• Mahrem: Baba, kardeş, oğul, amca, dayı vb.\n• Tek başına gidemez\n\n**Farz Olan Kişi:**\n• Geciktirmeden gitmelidir\n• 'Gelecek yıl giderim' demek doğru değil\n• Ömründe bir kez farzdır\n\n**Farz Olmayan:**\n• Çocuklar (sevap kazanır ama farz değil)\n• Fakirler\n• Hastalar\n• Mahremsiz kadınlar",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "hac",
        "question": "Hac için kaç para gerekir?",
        "answer": "2025 yılı hac bedelleri ve şartları:\n\n**Resmi Hac Bedeli (2025):**\n• Diyanet Kontenjanı: ~350.000 - 400.000 TL\n• Özel Acenteler: 450.000 - 600.000 TL\n• VIP Hizmetler: 800.000 TL+\n\n**Bedele Dahil Olanlar:**\n• Uçak bileti (gidiş-dönüş)\n• Konaklama (Mekke-Medine)\n• Otobüs transferleri\n• Rehberlik hizmeti\n• Hac sigortası\n• Vize işlemleri\n\n**Ekstra Masraflar:**\n• Kişisel harcamalar: 20.000-50.000 TL\n• Kurban (isteğe göre): 5.000-10.000 TL\n• Ziyaretler için ek ücretler\n• Hediye ve hediyelik eşya\n\n**Toplam Bütçe:**\n• Ortalama: 400.000 - 450.000 TL\n• Konforlu: 500.000 - 650.000 TL\n• Lüks: 800.000 TL+\n\n**Mali Şart:**\n• Hac masrafı + Evde kalanların 1 aylık nafakası\n• Borçlar ödendikten sonra\n• Dönüşte geçim kaynağı olmalı\n\n**Ödeme Şekilleri:**\n• Peşin ödeme (indirimli)\n• Taksitli ödeme planları\n• Erken kayıt avantajları\n\n**Başvuru:**\n• Diyanet: www.hac.diyanet.gov.tr\n• Kura sistemi ile\n• Erken başvuru şart",
        "source": "Diyanet İşleri Başkanlığı - 2025 Hac Bilgilendirmesi"
    },
    {
        "category": "hac",
        "question": "Haccın farzları nelerdir?",
        "answer": "Haccın 3 farzı (rüknü) vardır. Bunlardan biri yapılmazsa hac geçersizdir.\n\n**1. İHRAM (Niyet ve Telbiye)**\n• Mikattan ihrama girmek\n• Hac için niyet etmek\n• Telbiye getirmek: 'Lebbeyk Allahümme lebbeyk...'\n• İhram elbiseleri giymek\n\n**2. ARAFAT VAKFESİ**\n• En önemli rükündür\n• Zilhicce'nin 9. günü\n• Öğleden güneş batımına kadar\n• Arafat sınırları içinde olmak\n• En az bir dakika bile yeterli\n• 'Hac Arafat'tır' (Hadis)\n\n**3. ZIYARET TAVAFI (İFÂZE TAVAFI)**\n• Kâbe'yi 7 kez tavaf etmek\n• Bayramın 1., 2. veya 3. günü\n• Arafat'tan dönüşte\n• Cünüplükten temizlenmiş olmak\n\n**Bunlar Yapılmazsa:**\n• Hac geçersizdir\n• Telafi edilemez\n• Yeniden hac gerekir\n\n**Vacip Olanlar (Yapılmazsa Kurban):**\n• Safa-Merve arası sa'y\n• Şeytan taşlama (cemarat)\n• Traş olma veya kısaltma\n• Müzdelife'de vakit geçirmek\n• İhram kurallarına uymak\n\n**Sünnetler:**\n• Tavafta Hacer-i Esved'i öpmek\n• Tavafta remel yapmak\n• Mina'da konaklama\n• Hutbeyi dinlemek",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "hac",
        "question": "Hac çeşitleri nelerdir?",
        "answer": "Hac üç şekilde yapılır: İfrad, Temettu ve Kıran.\n\n**1. İFRAD HACCI**\n• Sadece hac için ihrama girilir\n• Umre yapılmaz\n• Kurban gerekmez\n• En sade hac şekli\n\n**Yapılışı:**\n• Mikattan hac niyetiyle ihrama gir\n• Mekke'ye gel\n• Tavaf ve sa'y yap (sünnet)\n• Arafat'a git\n• Haccı tamamla\n\n**2. TEMETTU HACCI (EN YAYGINI)**\n• Önce umre yapılır\n• İhramdan çıkılır\n• Sonra hac için tekrar ihrama girilir\n• Kurban kesilmesi gerekir\n\n**Yapılışı:**\n• Mikattan umre niyetiyle ihram\n• Umreyi tamamla (tavaf, sa'y, tıraş)\n• İhramdan çık, normal hayata dön\n• Zilhicce'nin 8'inde hac için ihram\n• Haccı tamamla\n• Kurban kes\n\n**3. KIRAN HACCI**\n• Hac ve umre beraber niyetlenir\n• İhramdan çıkılmaz\n• Kurban gerekir\n• Daha zor bir şekildir\n\n**Yapılışı:**\n• Mikattan hac ve umre birlikte niyetle ihram\n• Mekke'ye gel\n• Umre tavaf ve sa'yı yap\n• İhramdan çıkma\n• Arafat'a git\n• Haccı tamamla\n• Kurban kes\n\n**Hangisi Daha İyi?**\n• Temettu en kolay ve yaygın\n• İfrad kurban gerektirmez\n• Kıran en fazla sevap (zor olduğu için)\n\n**Türkiye'den Gidenler:**\n• Genelde Temettu tercih edilir\n• Diyanet rehberleri buna göre planlama yapar",
        "source": "Diyanet İşleri Başkanlığı - Hac Eğitim Platformu"
    },
    {
        "category": "hac",
        "question": "Dam (ceza kurbanı) ne zaman gerekir?",
        "answer": "Dam (ceza kurbanı), haccın vacip ve yasaklarına uyulmaması durumunda kesilir.\n\n**Dam Gerektiren Durumlar:**\n\n**1. Vakipleri Kaçırma:**\n• Müzdelife'de durmama\n• Mina'da konaklama yapılmazsa\n• Cemarat'ı (şeytan taşlama) zamanında yapılamama\n\n**2. İhram Yasaklarını Çiğneme:**\n• Dikişli elbise giymek (erkekler)\n• Başı örtmek (erkekler)\n• Tırnak kesmek\n• Saç kesmek/kısaltmak\n• Koku sürmek\n• Avlanmak\n• Cinsel ilişki (hac iptal, kaza gerekir)\n\n**3. Sa'y'ı Unutma:**\n• Safa-Merve arası koşu yapılmazsa\n• Sonradan hatırlayıp yapılabilir\n• Yapılamazsa dam\n\n**4. Tıraşı Yaptırıp Tavaf Etmeme:**\n• Sıra bozulursa\n• Tıraş önce, tavaf sonra olmamalı\n\n**Dam Çeşitleri:**\n\n**1. Kurban (Koyun/Keçi):**\n• En ağır ceza\n• Harem bölgesinde kesilir\n• Fakirlere dağıtılır\n\n**2. Oruç:**\n• Kurban kesemeyenler\n• 10 gün oruç (3 hacda, 7 döndükten sonra)\n\n**3. Sadaka:**\n• Daha hafif kusurlar için\n• 6 fakire yemek\n\n**Dam Kesim Yeri:**\n• Mekke Harem bölgesi\n• Mina, Arafat veya Mekke\n• Vekaletle kestirilebilir\n\n**Önemi:**\n• Haccın kusurunu kapatır\n• İhmal edilmemeli\n• Mümkünse hac sırasında",
        "source": "Diyanet İşleri Başkanlığı"
    },
    
    # ============ GÜNLÜK HAYAT KATEGORİSİ - EK SORULAR ============
    {
        "category": "gunluk",
        "question": "Anne baba hakları nelerdir?",
        "answer": "Anne ve babaya iyilik yapmak, İslam'ın en önemli emirlerindendir.\n\n**Kur'an'da Anne-Baba:**\n'Rabbin, sadece kendisine kulluk etmenizi ve anne-babaya iyilik yapmanızı emretti.' (İsra, 23)\n\n**Anne-Baba Hakları:**\n\n**1. Saygı ve İtaat:**\n• Sözlerini dinlemek\n• Emrlerine uymak (haramdışında)\n• Yüksek sesle konuşmamak\n• 'Öf' bile dememek\n• İsimlerini anarak çağırmamak\n\n**2. Mali Yardım:**\n• İhtiyaçlarını karşılamak\n• Bakım masrafları\n• Sağlık giderleri\n• Konforlu yaşam sağlamak\n\n**3. Manevi Destek:**\n• Ziyaret etmek\n• Telefon etmek\n• Yalnız bırakmamak\n• Sohbet etmek\n• Üzmemek\n\n**4. Hizmet Etmek:**\n• Yaşlılıkta yanlarında olmak\n• Hasta bakımı\n• Günlük işlerinde yardım\n• Sabırlı olmak\n\n**Öldükten Sonra:**\n• Dua etmek\n• Sadaka vermek\n• Borçlarını ödemek\n• Dostlarını gözetmek\n• Vasiyetlerini yerine getirmek\n\n**Hz. Peygamber:**\n'Cennet anaların ayakları altındadır.'\n\n'Babanın rızası Allah'ın rızasında, babanın öfkesi Allah'ın öfkesindedir.'\n\n**İtaat Sınırı:**\n• Allah'a isyanda itaat edilmez\n• Haramı emrederlerse yapılmaz\n• Ama yine de saygı gösterilir\n• Güzel sözle reddedilir\n\n**En Büyük Günah:**\n• Anne-babaya eziyet etmek\n• Âkü'l-vâlideyn (anne-babaya karşı gelmek)\n• Büyük günahların en büyüğüdür",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "Helal-haram yemek nasıl anlaşılır?",
        "answer": "İslam'da yiyecek ve içeceklerin helal-haram olması belirli kurallara bağlıdır.\n\n**HARAM YEMEKLER:**\n\n**1. Açıkça Haramlar:**\n• Domuz eti ve ürünleri\n• Kan ve kan ürünleri\n• Leş (ölü hayvan)\n• Allah adı anılmadan kesilen\n• İçki ve alkollü içecekler\n• Sarhoş edici maddeler\n\n**2. Haram Hayvanlar:**\n• Yırtıcı hayvanlar (aslan, kurt vb.)\n• Yırtıcı kuşlar (kartal, şahin vb.)\n• Köpek, kedi (mezhebe göre)\n• Eşek, katır\n• Böcekler (çekirge hariç)\n• Kurbağa, yılan, fare\n\n**3. Deniz Ürünleri:**\n• Balık helal (pullu balıklar)\n• Karides: Alimlere göre değişir\n• Midye, istiridye: Tartışmalı\n• Ahtapot: Çoğunluğa göre mekruh\n• Yengeç: Alimlere göre değişir\n\n**HELAL YEMEKLER:**\n\n**1. Kara Hayvanları:**\n• Sığır, koyun, keçi\n• Deve, tavuk, hindi\n• Tavşan, geyik\n• Bıldırcın, kumru\n\n**2. Deniz Ürünleri:**\n• Tüm balık çeşitleri\n• Çoğu deniz ürünü (ihtilaf var)\n\n**3. Bitkisel Gıdalar:**\n• Tüm sebze ve meyveler\n• Tahıllar\n• Bakliyatlar\n• Yağlar (zeytinyağı vb.)\n\n**KESİM ŞARTI:**\n• Müslüman veya Ehli Kitap kesmeli\n• Besmele çekilmeli\n• Şah damarı kesilmeli\n• Kan akıtılmalı\n• Hayvan acı çekmemeli\n\n**ŞÜPHEL GIDALAR:**\n• E kodları (bazıları domuz ürünü)\n• Jelatin (kaynak önemli)\n• Renklendirici ve katkılar\n• İhraç ürünleri (helal belgesi)\n\n**HELAL SERTİFİKA:**\n• TSE helal belgesi\n• Uluslararası helal sertifikalar\n• Güvenilir markaları tercih\n\n**Kur'an:**\n'Kendisine helal kılınanları haram, haram kılınanları helal sayan kimse, Allah'a iftira etmiş olur.' (Yusuf, 67)",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "İslam'da temizlik nasıl olmalı?",
        "answer": "Temizlik İslam'ın yarısıdır. (Hadis)\n\n**BEDEN TEMİZLİĞİ:**\n\n**1. Zorunlu Temizlik (Farz):**\n• Cünüplükten gusül\n• Hayızdan sonra gusül\n• Nifastan sonra gusül\n• Abdest alınması gereken durumlar\n• Necasetten (pislikten) temizlik\n\n**2. Gusül Alınacak Haller:**\n• Cinsel ilişki\n• İhtilam (rüyada boşalma)\n• Hayız ve nifas bitimi\n• Doğum sonrası\n• Cuma günü (sünnet)\n• Bayram günleri (sünnet)\n\n**3. Vücut Temizliği:**\n• Traş olmak (koltuk altı, kasık)\n• Tırnak kesmek\n• Diş temizliği (misvak)\n• Gusül (haftada 1)\n\n**ELBİSE TEMİZLİĞİ:**\n• Temiz elbise giymek\n• Pislik bulaşırsa yıkamak\n• Cuma için özel elbise\n• Koku sürülmesi (misk)\n\n**MEKAN TEMİZLİĞİ:**\n• Ev temizliği\n• Mescid temizliği\n• Sokak temizliği\n• Çevre temizliği\n\n**YİYECEK TEMİZLİĞİ:**\n• Yemek öncesi el yıkama\n• Temiz kaplar\n• Hijyenik pişirme\n• Kapalı saklama\n\n**SU TEMİZLİĞİ:**\n• Akan su temizdir\n• Durgun su şüphelidir\n• Pislik göze görünürse haram\n• Az su (külle değişir): 216 litre\n\n**ÇEVREYİ KİRLETMEMEK:**\n• Yola pislik dökmemek\n• Çöpü yerine atmak\n• Tükürük, balgam\n• Tuvalet adabı\n\n**Hz. Peygamber:**\n'Allah güzeldir, güzeli sever. Temizdir, temizi sever.'\n\n'Beş şey fıtrattandır: Sünnet olmak, traş olmak, tırnak kesmek, koltuk altı kıllarını almak, bıyığı kısaltmak.'\n\n**TUVALET ADABI:**\n• Sağ ayakla gir\n• Dua et\n• Sol el kullan\n• Su ile temizlen\n• Sol ayakla çık\n\n**MİSVAK:**\n• Diş temizliği için sünnet\n• Abdest öncesi\n• Uyku öncesi\n• Ağız kokusu giderme",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "İslam'da kadın hakları nelerdir?",
        "answer": "İslam kadına birçok hak ve değer vermiştir.\n\n**EĞİTİM HAKKI:**\n• İlim öğrenmek farz\n• Kadın ve erkek eşit\n• Hz. Peygamber: 'İlim öğrenmek her Müslümana farzdır'\n• Kadın sahabe (ashab) alimler yetiştirdi\n\n**MALİ HAKLAR:**\n• Mülk edinme hakkı\n• Ticaret yapma hakkı\n• Kendi malını istediği gibi kullanma\n• Mehir (evlilik hediyesi) alma\n• Miras hakkı\n• Çalışma hakkı\n\n**EVLİLİK HAKLARI:**\n• Evlenmeyi kabul/red hakkı\n• Zorla evlendirilemez\n• Mehir alma hakkı\n• Nafaka (geçim) hakkı\n• Eşinden iyi muamele görme\n• Boşanma talep etme (hul')\n\n**SOSYAL HAKLAR:**\n• Toplumda saygı görme\n• Tacize karşı korunma\n• İş hayatına katılma\n• Siyasi haklar (oy kullanma)\n• Sosyal faaliyetler\n\n**AİLEDEKİ YERİ:**\n• Anne: En yüksek makam\n• Kız: Babanın göz bebeği\n• Eş: Hayat arkadaşı\n• Kız kardeş: Korunması gereken\n\n**Kur'an:**\n'Erkekler kadınların koruyucusudur.' (Nisa, 34)\n'Onlarla güzellikle yaşayın.' (Nisa, 19)\n'Annelere saygı gösterin.' (Nisa, 1)\n\n**Hz. Peygamber:**\n'Cennet anaların ayakları altındadır.'\n'Hayırlınız, ailesine en iyi davrananınızdır.'\n'Kadınlara hayırla muamele ediniz.'\n\n**EŞLERİN BİRBİRİNE HAKLARI:**\n• Karşılıklı saygı\n• Güzel muamele\n• Maddi destek (erkek)\n• Ev işleri yardım\n• Cinsel haklar\n• Gizlilik\n\n**KORUMA HAKLARI:**\n• Şiddetten korunma\n• Zulümden korunma\n• Haksızlıktan korunma\n• Tacizden korunma\n\n**MİRAS HAKKI:**\n• Kadının miras hakkı var\n• Belli oranlarda\n• Hiçbir zaman mahrum edilemez\n\n**ÇALIŞMA HAKKI:**\n• Çalışabilir\n• Kazancı kendine ait\n• Ailesine vermek zorunda değil\n• İslami sınırlar içinde",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "gunluk",
        "question": "İslam'da hayvan hakları nelerdir?",
        "answer": "İslam, hayvanlara iyi davranmayı emreder.\n\n**TEMEL İLKELER:**\n'Allah her şeye güzel davranmayı farz kıldı.' (Hadis)\n\n**HAYVANLARA İYİLİK:**\n\n**1. Beslenme:**\n• Yeterli yemek vermek\n• Temiz su sağlamak\n• Aç bırakmamak\n• Zamanında yedirmek\n\n**2. Barınma:**\n• Uygun barınak\n• Sıcak/soğuktan koruma\n• Temiz ortam\n• Rahat etme alanı\n\n**3. Eziyet Etmemek:**\n• Dövmemek\n• İşkence yapmamak\n• Aç susuz bırakmamak\n• Fazla yük yüklememek\n• Güç yetirmediği iş yaptırmamak\n\n**4. Kesim Adabı:**\n• Keskin bıçak kullanmak\n• Hızlı kesmek\n• Hayvanı acı çektirmemek\n• Diğer hayvanların görmemesi\n• Besmele çekmek\n\n**YASAK DAVRANIŞLAR:**\n• Hayvanları dövmek\n• İşkence etmek\n• Boşuna öldürmek\n• Açlığa mahkum etmek\n• Oyun için avlanmak\n• Dövüştürmek\n• Hayvan deneyleri (gereksiz)\n\n**SEVİYAT KAZANDIRAN:**\n\nBir kadın, susuz bir köpeğe su verdiği için cennetlik oldu (Hadis)\n\nBir kadın, kediyi aç bıraktığı için cehenneme gitti (Hadis)\n\n**AVLANMA KURALLARI:**\n• İhtiyaç için avlanma\n• Oyun için değil\n• Besmele ile\n• Hızlı öldürme\n• Yavru avlanmaz\n• Gebe hayvan avlanmaz\n\n**KEDİ VE KÖPEK:**\n• Kedi: Temiz sayılır\n• Evde beslenebilir\n• Yemek artıkları verilebilir\n• Köpek: Tükürüğü necis\n• Bekçi, av için beslenir\n\n**HAYVAN HAKLARI:**\n• Dinlenme hakkı\n• Su-yemek hakkı\n• Sağlık hakkı\n• Doğal davranış hakkı\n• Eziyet görmeme hakkı\n\n**KURBAN VE AKIKA:**\n• Hayvan en az acı çekmeli\n• Keskin bıçak şart\n• Tek seferde kesmek\n• Diğer hayvanların görmemesi\n• Çevreyi kirletmemek",
        "source": "Diyanet İşleri Başkanlığı"
    },
    
    # ============ DUA VE ZİKİR - EK SORULAR ============
    {
        "category": "dua",
        "question": "İstihare duası nasıl yapılır?",
        "answer": "İstihare, önemli bir konuda Allah'tan hayır dilemektir.\n\n**İstihare Namazı:**\n\n**1. İki Rekat Namaz:**\n• Nafile olarak kılınır\n• Yatsıdan sonra veya teheccüd vaktinde\n• Birinci rekat: Fatiha + Kafirun\n• İkinci rekat: Fatiha + İhlas\n\n**2. Selam Verdikten Sonra:**\nİstihare duası okunur\n\n**İstihare Duası:**\n\n'Allahümme innî estahîrüke bi ilmike ve estakdirüke bi kudretike ve es'elüke min fadlikel-azîm, fe inneke takdiru ve lâ ekdiru ve ta'lemu ve lâ a'lemu ve ente allâmul-ğuyûb.\n\nAllahümme in kunte ta'lemu enne hâzel-emra (işini söyle) hayrun lî fî dînî ve maâşî ve âkıbeti emrî fakkdürhü lî ve yessirhu lî sümme bârik lî fîh.\n\nVe in kunte ta'lemu enne hâzel-emra şerrun lî fî dînî ve maâşî ve âkıbeti emrî fasrifhu annî vasrifnî anhu vaktür liyel-hayra haysü kâne sümme raddınî bih.'\n\n**Türkçe Anlamı:**\n'Allah'ım! Senin ilminle senden hayır dilerim, kudretinle güç isterim ve senden büyük lütfunu isterim. Çünkü sen her şeye gücü yeten, ben ise güçsüzüm. Sen bilen, ben bilmeyenim. Sen gaybı bilensin.\n\nAllah'ım! Eğer bu iş (işini söyle) benim dinim, dünyam ve işlerimin sonu bakımından hayırlı ise, onu benim için takdir et, kolaylaştır ve bereketli kıl.\n\nEğer bu iş benim için şerli ise, onu benden uzaklaştır, beni ondan uzaklaştır. Nerede olursa olsun hayırı bana nasip et ve beni onunla hoşnut kıl.'\n\n**NE ZAMAN YAPILIR:**\n• Evlilik kararı\n• İş değişikliği\n• Ev/araba alımı\n• Seyahat kararı\n• Önemli yatırımlar\n• Eğitim seçimi\n\n**NE YAPILMAZ:**\n• Haram işler için\n• Farz işleri için (namaz, oruç)\n• Küçük şeyler için\n\n**İstihare Sonrası:**\n• Rüya beklemek şart değil\n• Kalp rahatlığı önemli\n• Meşveret et (danış)\n• Tevekkül et\n• Kararını ver\n• Allah'a güven\n\n**İşaretler:**\n• Kalp huzuru: Hayırlıdır\n• Kalp sıkıntısı: Hayırlı değildir\n• Kolaylaşma: İyi işaret\n• Zorluklar: Sakınca olabilir\n\n**Kaç Kez Yapılır:**\n• Bir kez yeterli\n• 3-7 kez tekrarlanabilir\n• Kalp tatmin olana kadar\n\n**Önemli:**\n• İstihare yapıp durumu Allah'a havale et\n• Sonuca razı ol\n• Pişmanlık duyma\n• Her şey hayırlısınadır",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "dua",
        "question": "Kelime-i tevhid nedir ve fazileti nedir?",
        "answer": "Kelime-i Tevhid, İslam'ın temel inancının ifadesidir.\n\n**KELİME-İ TEVHİD:**\n\n'Lâ ilâhe illallah, Muhammedün Resûlüllah'\n\n**Anlamı:**\n'Allah'tan başka ilah yoktur, Muhammed Allah'ın elçisidir.'\n\n**İki Şahadet:**\n\n**1. Allah'ın Birliği:**\n'Lâ ilâhe illallah' (Allah'tan başka ilah yok)\n• Tevhid: Allah'ın birliği\n• Şirk: Allah'a ortak koşma (en büyük günah)\n• İman'ın temeli\n\n**2. Peygamberlik:**\n'Muhammedün Resûlüllah' (Muhammed Allah'ın elçisi)\n• Hz. Muhammed son peygamber\n• Onun getirdiği din: İslam\n• Risaletini tasdik etmek\n\n**FAZİLETİ:**\n\nHz. Peygamber buyurdu:\n'Kim içten inanarak Lâ ilâhe illallah derse, cennete girer.'\n\n'Kelime-i tevhid her şeyi yıkar (günahları), hiçbir şey onu yıkamaz.'\n\n'En hayırlı zikir Lâ ilâhe illallah'tır.'\n\n**NE ZAMAN OKUNUR:**\n• Sabah-akşam 100 defa\n• Namaz tesbihatında\n• Yatmadan önce\n• Her zaman\n• Tesbihte\n• Ölüm döşeğinde (telkin)\n\n**UZUN ŞEKLİ:**\n\n'Lâ ilâhe illallahu vahdehû lâ şerîke leh, lehul-mülkü ve lehul-hamdü ve hüve alâ külli şey'in kadîr'\n\n**Anlamı:**\n'Allah'tan başka ilah yoktur. O tektir, ortağı yoktur. Mülk O'nundur, hamd O'na mahsustur ve O her şeye kadirdir.'\n\n**SEVİYATI:**\n• 100 defa okuyan: 10 köle azat etmiş gibi\n• Şeytan uzaklaşır\n• Günahlar silinir\n• Cennet müjdesi\n\n**EZAN SONRASI:**\nEzan'dan sonra şehadet getirmek sünnettir ve faziletlidir.\n\n**MÜSLÜMAN OLMAK:**\nKelime-i şehadet getirmekle Müslüman olunur.",
        "source": "Diyanet İşleri Başkanlığı"
    },
    {
        "category": "dua",
        "question": "Kaza namazı nasıl kılınır?",
        "answer": "Kaza namazı, vaktinde kılınamayan farz namazların kazasıdır.\n\n**KAZA GEREKTİREN DURUMLAR:**\n• Unutmak\n• Uyuyakalmak\n• Bayılmak\n• Özürsüz terk etmek (günah)\n\n**KAZA KILMAK:**\n• Farz ve vâcip namazların kazası olur\n• Sünnet namazların kazası olmaz (sadece vitir)\n• Cuma namazı: 4 rekat öğle olarak kaza\n• Bayram namazı: Kazası yok\n\n**KAZA NAMAZI KILIMI:**\n\n**1. Niyet:**\n• Hangi namazın kazası olduğu niyetlenir\n• 'Sabah namazının kazasını kılmaya niyet ettim'\n\n**2. Sıralama:**\n• Fazla değilse (5-6 namazdan az) sırayla\n• Çok fazla ise sırasız kılınabilir\n• İlk vakit farzı önce\n\n**3. Kılım Şekli:**\n• Normal namaz gibi\n• İki rekat sabah\n• Dört rekat öğle\n• Dört rekat ikindi\n• Üç rekat akşam\n• Dört rekat yatsı\n• Üç rekat vitir\n\n**KAZA NE ZAMAN KILINIR:**\n• Hatırlayınca hemen\n• Mekruh vakitler hariç (güneş doğuşu, tepe, batış)\n• Vakit namazından önce veya sonra\n• Gece kılınabilir\n• Cuma namazında ara verilebilir\n\n**ÇOK KAZA VAR İSE:**\n• Tahmin edilir\n• Emin olunana kadar kılınır\n• Günlük 1-2 kaza eklenebilir\n• Yavaş yavaş tamamlanır\n\n**VITIR KAZASI:**\n• Sabah namazından önce kılınır\n• İkişer rekat + son 1 rekat\n• Kunut duası okunur\n\n**CUMA NAMAZI KAZASI:**\n• 4 rekat öğle namazı olarak\n• Sünnetleriyle birlikte\n\n**ÖNEMLI NOKTALAR:**\n• Kaza borcu ölünceye kadar kalır\n• Vasiyetle fidye verilebilir\n• Telafi edilmesi gerekir\n• Günah olsa bile kaza şart\n\n**KAZA NAMAZINDA:**\n• Farz + Vitir kılınır\n• Sünnetler kılınmaz\n• Sadece farz kısımlar\n\n**ÖRN ERIM:**\nSabah namazını kaçırdım:\n• 2 rekat sabah farzı kaza\n• Sünnetleri değil\n\n**TAVSİYE:**\n• Günlük 1-2 kaza ekle\n• Teheccüd vaktinde kıl\n• Topluca kılınabilir\n• Yılda 1 ay tatilde halledilebilir",
        "source": "Diyanet İşleri Başkanlığı"
    }
]
